/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GenenanetExportPanel.java
 *
 * Created on 21 mai 2011, 18:27:08
 */
package org.ancestris.ancestrisexports.geneanet;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.openide.util.NbBundle;
import org.openide.util.NbPreferences;

/**
 *
 * @author dominique
 */
public class GenenanetExportPanel extends javax.swing.JPanel {

    private File file = null;
    private String gedcomName = "";
    // get export directoty
    String exportDir = "";
    String exportFile = "";

    /** Creates new form GenenanetExportPanel */
    public GenenanetExportPanel(String gedcomName) {
        this.gedcomName = gedcomName;
        exportDir = NbPreferences.forModule(GenenanetExportPanel.class).get("Dossier Export " + gedcomName, "");
        exportFile = NbPreferences.forModule(GenenanetExportPanel.class).get("Fichier Export " + gedcomName, gedcomName + ".gw");
        initComponents();
        file = new File(jTextFieldExportFileName.getText());

        if (NbPreferences.forModule(GenenanetExportPanel.class).get("Less100", "false").equals("true")) {
            jRadioButtonLess100Yes.setSelected(true);
        } else {
            jRadioButtonLess100No.setSelected(true);
        }

        if (NbPreferences.forModule(GenenanetExportPanel.class).get("ExportEvents", "true").equals("true")) {
            jRadioButtonEventsYes.setSelected(true);
        } else {
            jRadioButtonEventsNo.setSelected(true);
        }

        if (NbPreferences.forModule(GenenanetExportPanel.class).get("ExportNotes", "true").equals("true")) {
            jRadioButtonNotesYes.setSelected(true);
        } else {
            jRadioButtonNotesNo.setSelected(true);
        }

        if (NbPreferences.forModule(GenenanetExportPanel.class).get("ExportSources", "true").equals("true")) {
            jRadioButtonSourcesYes.setSelected(true);
        } else {
            jRadioButtonSourcesNo.setSelected(true);
        }
    }

    public File getFile() {
        return file;
    }

    public boolean isNotesExported() {
        return buttonGroupNotes.getSelection().equals(jRadioButtonNotesYes);
    }

    public boolean isSourcesExported() {
        return buttonGroupSources.getSelection().equals(jRadioButtonSourcesYes);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroupEvents = new javax.swing.ButtonGroup();
        buttonGroupNotes = new javax.swing.ButtonGroup();
        buttonGroupSources = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonLess100Yes = new javax.swing.JRadioButton();
        jRadioButtonLess100No = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonEventsYes = new javax.swing.JRadioButton();
        jRadioButtonEventsNo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonNotesYes = new javax.swing.JRadioButton();
        jRadioButtonNotesNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonSourcesYes = new javax.swing.JRadioButton();
        jRadioButtonSourcesNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldExportFileName = new javax.swing.JTextField();
        jButtonChooseFile = new javax.swing.JButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jLabel1.text")); // NOI18N

        buttonGroup1.add(jRadioButtonLess100Yes);
        jRadioButtonLess100Yes.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jRadioButtonLess100Yes.text")); // NOI18N
        jRadioButtonLess100Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLess100YesActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonLess100No);
        jRadioButtonLess100No.setSelected(true);
        jRadioButtonLess100No.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jRadioButtonLess100No.text")); // NOI18N
        jRadioButtonLess100No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLess100NoActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jLabel2.text")); // NOI18N

        buttonGroupEvents.add(jRadioButtonEventsYes);
        jRadioButtonEventsYes.setSelected(true);
        jRadioButtonEventsYes.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jRadioButtonEventsYes.text")); // NOI18N
        jRadioButtonEventsYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEventsYesActionPerformed(evt);
            }
        });

        buttonGroupEvents.add(jRadioButtonEventsNo);
        jRadioButtonEventsNo.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jRadioButtonEventsNo.text")); // NOI18N
        jRadioButtonEventsNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEventsNoActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jLabel3.text")); // NOI18N

        buttonGroupNotes.add(jRadioButtonNotesYes);
        jRadioButtonNotesYes.setSelected(true);
        jRadioButtonNotesYes.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jRadioButtonNotesYes.text")); // NOI18N
        jRadioButtonNotesYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNotesYesActionPerformed(evt);
            }
        });

        buttonGroupNotes.add(jRadioButtonNotesNo);
        jRadioButtonNotesNo.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jRadioButtonNotesNo.text")); // NOI18N
        jRadioButtonNotesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNotesNoActionPerformed(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jLabel5.text")); // NOI18N

        buttonGroupSources.add(jRadioButtonSourcesYes);
        jRadioButtonSourcesYes.setSelected(true);
        jRadioButtonSourcesYes.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jRadioButtonSourcesYes.text")); // NOI18N
        jRadioButtonSourcesYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSourcesYesActionPerformed(evt);
            }
        });

        buttonGroupSources.add(jRadioButtonSourcesNo);
        jRadioButtonSourcesNo.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jRadioButtonSourcesNo.text")); // NOI18N
        jRadioButtonSourcesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSourcesNoActionPerformed(evt);
            }
        });

        jLabel4.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jLabel4.text")); // NOI18N

        jTextFieldExportFileName.setText(exportDir + System.getProperty("file.separator") + exportFile);

        jButtonChooseFile.setText(org.openide.util.NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.jButtonChooseFile.text")); // NOI18N
        jButtonChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldExportFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonChooseFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonSourcesYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSourcesNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonNotesYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNotesNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonLess100Yes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonLess100No))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonEventsYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEventsNo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonLess100Yes)
                    .addComponent(jRadioButtonLess100No))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonEventsYes)
                    .addComponent(jRadioButtonEventsNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButtonNotesYes)
                    .addComponent(jRadioButtonNotesNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonSourcesYes)
                    .addComponent(jRadioButtonSourcesNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldExportFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseFileActionPerformed
        final FileNameExtensionFilter filter = new FileNameExtensionFilter(NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.fileType"), "gw");
        JFileChooser fc = new JFileChooser() {

            @Override
            public void approveSelection() {
                File f = getSelectedFile();
                if (f.exists() && getDialogType() == SAVE_DIALOG) {
                    int result = JOptionPane.showConfirmDialog(this, NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.Overwrite.Text"), NbBundle.getMessage(GenenanetExportPanel.class, "GenenanetExportPanel.Overwrite.Title"), JOptionPane.YES_NO_CANCEL_OPTION);
                    switch (result) {
                        case JOptionPane.YES_OPTION:
                            super.approveSelection();
                            return;
                        case JOptionPane.NO_OPTION:
                            return;
                        case JOptionPane.CANCEL_OPTION:
                            super.cancelSelection();
                            return;
                    }
                } else {
                    if (filter.accept(f) == false) {
                        setSelectedFile(new File(f.getName() + ".gw"));
                    }
                }
                super.approveSelection();
            }
        };

        if (exportDir.length() > 0) {
            File initialDir = new File(exportDir);
            // Set the current directory
            fc.setCurrentDirectory(initialDir);
        }

        fc.setFileFilter(filter);
        fc.setAcceptAllFileFilterUsed(false);
        fc.setSelectedFile(new File(exportFile));

        if (fc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            // Get current directory
            try {
                exportDir = fc.getCurrentDirectory().getCanonicalPath();
            } catch (IOException ex) {
                exportDir = "";
            }
            // save export directory
            NbPreferences.forModule(GenenanetExportPanel.class).put("Dossier Export " + gedcomName, exportDir);
            NbPreferences.forModule(GenenanetExportPanel.class).put("Fichier Export " + gedcomName, file.getName());
            jTextFieldExportFileName.setText(exportDir + System.getProperty("file.separator") + file.getName());
        }
    }//GEN-LAST:event_jButtonChooseFileActionPerformed

    private void jRadioButtonLess100YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLess100YesActionPerformed
        NbPreferences.forModule(GenenanetExportPanel.class).put("Less100", "true");
    }//GEN-LAST:event_jRadioButtonLess100YesActionPerformed

    private void jRadioButtonLess100NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLess100NoActionPerformed
        NbPreferences.forModule(GenenanetExportPanel.class).put("Less100", "false");
    }//GEN-LAST:event_jRadioButtonLess100NoActionPerformed

    private void jRadioButtonEventsYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEventsYesActionPerformed
        NbPreferences.forModule(GenenanetExportPanel.class).put("ExportEvents", "true");
    }//GEN-LAST:event_jRadioButtonEventsYesActionPerformed

    private void jRadioButtonEventsNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEventsNoActionPerformed
        NbPreferences.forModule(GenenanetExportPanel.class).put("ExportEvents", "false");
    }//GEN-LAST:event_jRadioButtonEventsNoActionPerformed

    private void jRadioButtonNotesYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNotesYesActionPerformed
        NbPreferences.forModule(GenenanetExportPanel.class).put("ExportNotes", "true");
    }//GEN-LAST:event_jRadioButtonNotesYesActionPerformed

    private void jRadioButtonNotesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNotesNoActionPerformed
        NbPreferences.forModule(GenenanetExportPanel.class).put("ExportNotes", "false");
    }//GEN-LAST:event_jRadioButtonNotesNoActionPerformed

    private void jRadioButtonSourcesYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSourcesYesActionPerformed
        NbPreferences.forModule(GenenanetExportPanel.class).put("ExportSources", "true");
    }//GEN-LAST:event_jRadioButtonSourcesYesActionPerformed

    private void jRadioButtonSourcesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSourcesNoActionPerformed
        NbPreferences.forModule(GenenanetExportPanel.class).put("ExportSources", "false");
    }//GEN-LAST:event_jRadioButtonSourcesNoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupEvents;
    private javax.swing.ButtonGroup buttonGroupNotes;
    private javax.swing.ButtonGroup buttonGroupSources;
    private javax.swing.JButton jButtonChooseFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonEventsNo;
    private javax.swing.JRadioButton jRadioButtonEventsYes;
    private javax.swing.JRadioButton jRadioButtonLess100No;
    private javax.swing.JRadioButton jRadioButtonLess100Yes;
    private javax.swing.JRadioButton jRadioButtonNotesNo;
    private javax.swing.JRadioButton jRadioButtonNotesYes;
    private javax.swing.JRadioButton jRadioButtonSourcesNo;
    private javax.swing.JRadioButton jRadioButtonSourcesYes;
    private javax.swing.JTextField jTextFieldExportFileName;
    // End of variables declaration//GEN-END:variables
}
