/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LanguageSelectionPanel.java
 *
 * Created on 16 juin 2011, 23:11:29
 */
package org.ancestris.trancestris.editors.actions;

import java.util.HashMap;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import org.ancestris.trancestris.editors.EditorTopComponent;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 *
 * @author dominique
 */
public class LanguageSelectionPanel extends javax.swing.JPanel {

    final static Locale[] locales = Locale.getAvailableLocales();
    final static HashMap<String, Locale> localeList = new HashMap<String, Locale>();

    private class LocaleComboBoxModel extends DefaultComboBoxModel {

        public LocaleComboBoxModel() {
            super();
            for (Locale locale : locales) {
                localeList.put(locale.getDisplayLanguage(), locale);
            }
        }
        Locale selectedLocale = new java.util.Locale("es", "ES");

        @Override
        public int getSize() {
            return localeList.size();
        }

        @Override
        public Object getElementAt(int i) {
            return locales[i].getDisplayLanguage();
        }

        @Override
        public void setSelectedItem(Object o) {
            selectedLocale = localeList.get((String) o);
        }

        @Override
        public Object getSelectedItem() {
            return selectedLocale.getDisplayLanguage();
        }
    }

    /** Creates new form LanguageSelectionPanel */
    public LanguageSelectionPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox(new LocaleComboBoxModel());

        setMaximumSize(new java.awt.Dimension(32789, 24));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/ancestris/trancestris/editors/actions/translate.gif"))); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(LanguageSelectionPanel.class, "LanguageSelectionPanel.jLabel1.text")); // NOI18N
        add(jLabel1);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        TopComponent tc = WindowManager.getDefault().findTopComponent("EditorTopComponent");
        ((EditorTopComponent) tc).setLocale((Locale) localeList.get((String)jComboBox1.getSelectedItem()));
    }//GEN-LAST:event_jComboBox1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
