package ancestris.modules.gedcom.searchduplicates;

import static ancestris.modules.gedcom.searchduplicates.Bundle.CheckDuplicatesVisualPanel3_title;
import ancestris.modules.gedcom.utilities.matchers.IndiMatcherOptions;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;
import org.openide.util.NbBundle;

@NbBundle.Messages("CheckDuplicatesVisualPanel3.title=Individuals search options")
public final class SearchDuplicatesVisualPanel3 extends JPanel {

    IndiMatcherOptions indiMatcherOptions = new IndiMatcherOptions();

    /**
     * Creates new form SearchDuplicatesVisualPanel2
     */
    public SearchDuplicatesVisualPanel3() {
        initComponents();
    }

    @Override
    public String getName() {
        return CheckDuplicatesVisualPanel3_title();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emptyPanel = new javax.swing.JPanel();
        sourcesOptionPanel1 = new javax.swing.JPanel();
        submittersOptionPanel = new javax.swing.JPanel();
        repositoriesOptionPanel = new javax.swing.JPanel();
        indiMaximumDateIntervalLabel = new javax.swing.JLabel();
        indiMaxDateIntervalSpinner = new javax.swing.JSpinner(new SpinnerNumberModel(365,0,3650,1));
        indiEmptyValuesValidRadioButton = new javax.swing.JRadioButton();
        indiAllFirstNamesRadioButton = new javax.swing.JRadioButton();
        indiCheckAllNamesRadioButton = new javax.swing.JRadioButton();
        indiCheckFamiliesRadioButton = new javax.swing.JRadioButton();

        javax.swing.GroupLayout emptyPanelLayout = new javax.swing.GroupLayout(emptyPanel);
        emptyPanel.setLayout(emptyPanelLayout);
        emptyPanelLayout.setHorizontalGroup(
            emptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        emptyPanelLayout.setVerticalGroup(
            emptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sourcesOptionPanel1Layout = new javax.swing.GroupLayout(sourcesOptionPanel1);
        sourcesOptionPanel1.setLayout(sourcesOptionPanel1Layout);
        sourcesOptionPanel1Layout.setHorizontalGroup(
            sourcesOptionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        sourcesOptionPanel1Layout.setVerticalGroup(
            sourcesOptionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout submittersOptionPanelLayout = new javax.swing.GroupLayout(submittersOptionPanel);
        submittersOptionPanel.setLayout(submittersOptionPanelLayout);
        submittersOptionPanelLayout.setHorizontalGroup(
            submittersOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        submittersOptionPanelLayout.setVerticalGroup(
            submittersOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout repositoriesOptionPanelLayout = new javax.swing.GroupLayout(repositoriesOptionPanel);
        repositoriesOptionPanel.setLayout(repositoriesOptionPanelLayout);
        repositoriesOptionPanelLayout.setHorizontalGroup(
            repositoriesOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
        repositoriesOptionPanelLayout.setVerticalGroup(
            repositoriesOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(indiMaximumDateIntervalLabel, org.openide.util.NbBundle.getMessage(SearchDuplicatesVisualPanel3.class, "SearchDuplicatesVisualPanel3.indiMaximumDateIntervalLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(indiEmptyValuesValidRadioButton, org.openide.util.NbBundle.getMessage(SearchDuplicatesVisualPanel3.class, "SearchDuplicatesVisualPanel3.indiEmptyValuesValidRadioButton.text")); // NOI18N

        indiAllFirstNamesRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(indiAllFirstNamesRadioButton, org.openide.util.NbBundle.getMessage(SearchDuplicatesVisualPanel3.class, "SearchDuplicatesVisualPanel3.indiAllFirstNamesRadioButton.text")); // NOI18N

        indiCheckAllNamesRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(indiCheckAllNamesRadioButton, org.openide.util.NbBundle.getMessage(SearchDuplicatesVisualPanel3.class, "SearchDuplicatesVisualPanel3.indiCheckAllNamesRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(indiCheckFamiliesRadioButton, org.openide.util.NbBundle.getMessage(SearchDuplicatesVisualPanel3.class, "SearchDuplicatesVisualPanel3.indiCheckFamiliesRadioButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(indiMaximumDateIntervalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(indiMaxDateIntervalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(indiAllFirstNamesRadioButton)
                            .addComponent(indiCheckAllNamesRadioButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(indiEmptyValuesValidRadioButton)
                            .addComponent(indiCheckFamiliesRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indiMaxDateIntervalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indiMaximumDateIntervalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indiEmptyValuesValidRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indiAllFirstNamesRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indiCheckAllNamesRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indiCheckFamiliesRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel emptyPanel;
    private javax.swing.JRadioButton indiAllFirstNamesRadioButton;
    private javax.swing.JRadioButton indiCheckAllNamesRadioButton;
    private javax.swing.JRadioButton indiCheckFamiliesRadioButton;
    private javax.swing.JRadioButton indiEmptyValuesValidRadioButton;
    private javax.swing.JSpinner indiMaxDateIntervalSpinner;
    private javax.swing.JLabel indiMaximumDateIntervalLabel;
    private javax.swing.JPanel repositoriesOptionPanel;
    private javax.swing.JPanel sourcesOptionPanel1;
    private javax.swing.JPanel submittersOptionPanel;
    // End of variables declaration//GEN-END:variables

    public IndiMatcherOptions getSelectedOptions() {
        indiMatcherOptions.setDateinterval((Integer) indiMaxDateIntervalSpinner.getValue());
        indiMatcherOptions.setCheckAllNames(indiCheckAllNamesRadioButton.isSelected());
        indiMatcherOptions.setAllFirstNames(indiAllFirstNamesRadioButton.isSelected());
        indiMatcherOptions.setCheckFamilies(indiCheckFamiliesRadioButton.isSelected());
        indiMatcherOptions.setEmptyValueValid(indiEmptyValuesValidRadioButton.isSelected());
        return indiMatcherOptions;
    }
}
