package ancestris.modules.familygroups;

import org.openide.util.NbPreferences;

final class FamilyGroupsOptionPanel extends javax.swing.JPanel {

    private final FamilyGroupsOptionsPanelController controller;

    FamilyGroupsOptionPanel(FamilyGroupsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minGroupSizeFormattedTextField = new javax.swing.JFormattedTextField();
        minGroupSizeLabel = new javax.swing.JLabel();
        maxGroupSizeLabel = new javax.swing.JLabel();
        maxGroupSizeFormattedTextField = new javax.swing.JFormattedTextField();

        minGroupSizeFormattedTextField.setColumns(3);
        minGroupSizeFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minGroupSizeFormattedTextField.setToolTipText(org.openide.util.NbBundle.getMessage(FamilyGroupsOptionPanel.class, "FamilyGroupsOptionPanel.minGroupSizeFormattedTextField.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(minGroupSizeLabel, org.openide.util.NbBundle.getMessage(FamilyGroupsOptionPanel.class, "FamilyGroupsOptionPanel.minGroupSizeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maxGroupSizeLabel, org.openide.util.NbBundle.getMessage(FamilyGroupsOptionPanel.class, "FamilyGroupsOptionPanel.maxGroupSizeLabel.text")); // NOI18N

        maxGroupSizeFormattedTextField.setColumns(3);
        maxGroupSizeFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxGroupSizeFormattedTextField.setToolTipText(org.openide.util.NbBundle.getMessage(FamilyGroupsOptionPanel.class, "FamilyGroupsOptionPanel.maxGroupSizeFormattedTextField.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGroupSizeLabel)
                    .addComponent(minGroupSizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGroupSizeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGroupSizeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minGroupSizeLabel)
                    .addComponent(minGroupSizeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxGroupSizeLabel)
                    .addComponent(maxGroupSizeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        minGroupSizeFormattedTextField.setValue(NbPreferences.forModule(OpenFamilyGroupsAction.class).get("minGroupSize", "2"));
        maxGroupSizeFormattedTextField.setValue(NbPreferences.forModule(OpenFamilyGroupsAction.class).get("maxGroupSize", "20"));
    }

    void store() {
        NbPreferences.forModule(FamilyGroupsOptionPanel.class).put("minGroupSize", String.valueOf(minGroupSizeFormattedTextField.getValue()));
        NbPreferences.forModule(FamilyGroupsOptionPanel.class).put("maxGroupSize", String.valueOf(maxGroupSizeFormattedTextField.getValue()));
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField maxGroupSizeFormattedTextField;
    private javax.swing.JLabel maxGroupSizeLabel;
    private javax.swing.JFormattedTextField minGroupSizeFormattedTextField;
    private javax.swing.JLabel minGroupSizeLabel;
    // End of variables declaration//GEN-END:variables
}
