/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultimediaLinkBeanPanel.java
 *
 * Created on 23 oct. 2010, 16:24:23
 */
package genjfr.app.editorstd.beans;

import genj.gedcom.Entity;
import genj.gedcom.Gedcom;
import genj.gedcom.Media;
import genj.gedcom.Property;
import genj.gedcom.PropertyXRef;
import genjfr.app.editorstd.media.JListWithMedia;
import genjfr.app.editorstd.media.MediaWrapper;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.text.JTextComponent;
import org.openide.util.Exceptions;

/**
 *
 * @author frederic
 */
public class MultimediaLinkBeanPanel extends BeanPanelParent implements PropertyChangeListener {

    private Entity[] mediaEntitiesList = new Entity[1];
    private MediaWrapper[] mediaList = new MediaWrapper[1];
    private boolean busy = false;
    //
    private FieldInputVerifier verifier = new FieldInputVerifier();

    /** Creates new form MultimediaLinkBeanPanel */
    public MultimediaLinkBeanPanel() {
        initComponents();
    }

    public void init() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multimediaLinkBean = new genjfr.app.editorstd.beans.MultimediaLinkBean();
        mediaTypeGroup = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mediaListBox = new JListWithMedia(mediaList);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        xref_obje = new javax.swing.JComboBox(mediaEntitiesList);
        jLabel2 = new javax.swing.JLabel();
        descriptive_title = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        multimedia_format = new javax.swing.JTextField();
        multimedia_file_reference = new javax.swing.JTextField();
        fileSearchButton = new javax.swing.JButton();
        mediaTabbedPane = new javax.swing.JTabbedPane();
        mediaPanel = new genjfr.app.editorstd.media.MediaPanel();
        noteStructureBeanPanel = new genjfr.app.editorstd.beans.NoteStructureBeanPanel();
        internalMediaButton = new javax.swing.JRadioButton();
        externalMediaButton = new javax.swing.JRadioButton();

        jSplitPane1.setOpaque(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(120, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 314));

        mediaListBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mediaListBox.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mediaListBoxValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mediaListBox);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        jButton1.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.jButton1.text")); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(29, 29));

        jButton2.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.jButton2.text")); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(29, 29));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        xref_obje.setEditable(true);
        xref_obje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xref_objeItemStateChanged(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.jLabel2.text")); // NOI18N

        descriptive_title.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.descriptive_title.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.jLabel3.text")); // NOI18N

        multimedia_format.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.multimedia_format.text")); // NOI18N

        multimedia_file_reference.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.multimedia_file_reference.text")); // NOI18N

        fileSearchButton.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.fileSearchButton.text")); // NOI18N
        fileSearchButton.setMaximumSize(new java.awt.Dimension(29, 29));
        fileSearchButton.setMinimumSize(new java.awt.Dimension(29, 29));
        fileSearchButton.setPreferredSize(new java.awt.Dimension(29, 29));
        fileSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSearchButtonActionPerformed(evt);
            }
        });

        mediaTabbedPane.addTab(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.mediaPanel.TabConstraints.tabTitle"), mediaPanel); // NOI18N
        mediaTabbedPane.addTab(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.noteStructureBeanPanel.TabConstraints.tabTitle"), noteStructureBeanPanel); // NOI18N

        mediaTypeGroup.add(internalMediaButton);
        internalMediaButton.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.internalMediaButton.text")); // NOI18N
        internalMediaButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                internalMediaButtonItemStateChanged(evt);
            }
        });
        internalMediaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internalMediaButtonActionPerformed(evt);
            }
        });

        mediaTypeGroup.add(externalMediaButton);
        externalMediaButton.setText(org.openide.util.NbBundle.getMessage(MultimediaLinkBeanPanel.class, "MultimediaLinkBeanPanel.externalMediaButton.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mediaTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(internalMediaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(externalMediaButton, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(multimedia_file_reference, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fileSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(xref_obje, 0, 236, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(descriptive_title, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(multimedia_format, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xref_obje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(internalMediaButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(externalMediaButton)
                            .addComponent(multimedia_file_reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fileSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(descriptive_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multimedia_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(mediaTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 206, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mediaListBoxValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mediaListBoxValueChanged
        if (evt.getValueIsAdjusting() && (mediaListBox.getSelectedIndex() > -1) && (mediaListBox.getSelectedIndex() < mediaListBox.getModel().getSize())) {
            displayMedia(mediaList[mediaListBox.getSelectedIndex()].getPropertyParent());
        }
    }//GEN-LAST:event_mediaListBoxValueChanged

    private void internalMediaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internalMediaButtonActionPerformed
        enableFields(internalMediaButton.isSelected());
    }//GEN-LAST:event_internalMediaButtonActionPerformed

    private void xref_objeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xref_objeItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Select item in list box if already there, clear selection otherwise
            Entity selectedEntity = (Entity) xref_obje.getSelectedItem();
            boolean found = false;
            for (int i = 0; i < mediaList.length; i++) {
                Property property = mediaList[i].getPropertyParent();
                if (property instanceof PropertyXRef) {
                    PropertyXRef pRef = (PropertyXRef) property;
                    Entity entity = pRef.getTargetEntity();
                    if (entity instanceof Media && entity == selectedEntity) {
                        if (!busy) {
                            mediaListBox.setSelectedIndex(i);
                        }
                        found = true;
                        break;
                    }
                }
            }
            if (!found) {
                mediaListBox.clearSelection();
            }
            //
            displayProperties((Property) xref_obje.getSelectedItem());
        }
    }//GEN-LAST:event_xref_objeItemStateChanged

    private void internalMediaButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_internalMediaButtonItemStateChanged
        enableFields(internalMediaButton.isSelected());
    }//GEN-LAST:event_internalMediaButtonItemStateChanged

    private void fileSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSearchButtonActionPerformed
        String str = multimedia_file_reference.getText();
        JFileChooser fc = new JFileChooser(str != null ? str.substring(0, Math.max(str.indexOf(" "), str.length())) : "");
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String relPath = RelativePath.getRelativePath(parentProperty.getGedcom().getOrigin().getFile(), fc.getSelectedFile());
            multimedia_file_reference.setText(relPath);
        }
    }//GEN-LAST:event_fileSearchButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descriptive_title;
    private javax.swing.JRadioButton externalMediaButton;
    private javax.swing.JButton fileSearchButton;
    private javax.swing.JRadioButton internalMediaButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList mediaListBox;
    private genjfr.app.editorstd.media.MediaPanel mediaPanel;
    private javax.swing.JTabbedPane mediaTabbedPane;
    private javax.swing.ButtonGroup mediaTypeGroup;
    private genjfr.app.editorstd.beans.MultimediaLinkBean multimediaLinkBean;
    private javax.swing.JTextField multimedia_file_reference;
    private javax.swing.JTextField multimedia_format;
    private genjfr.app.editorstd.beans.NoteStructureBeanPanel noteStructureBeanPanel;
    private javax.swing.JComboBox xref_obje;
    // End of variables declaration//GEN-END:variables

    public void setProperties(Property parentProperty) {
        this.parentProperty = parentProperty;
        // set lists
        initEntitiesList();
        initMediaList();
        if (mediaListBox.getModel().getSize() > 0) {
            mediaListBox.setSelectedIndex(0);
            displayMedia(mediaList[mediaListBox.getSelectedIndex()].getPropertyParent()); // state changed not adjusting at initialisation so force display
        }
        enableFields(internalMediaButton.isSelected());
        // set the rest
//        addressStructure.setAddr((PropertyMultilineValue) (parentProperty.getProperty(AddressStructureBean.PROP_ADDR)));
//        if (addressStructure.getAddr() != null) {
//            addressStructure.setAddr1((PropertySimpleValue) (addressStructure.getAddr().getProperty(AddressStructureBean.PROP_ADDR1)));
//            addressStructure.setAddr2((PropertySimpleValue) (addressStructure.getAddr().getProperty(AddressStructureBean.PROP_ADDR2)));
//            addressStructure.setCity((PropertyChoiceValue) (addressStructure.getAddr().getProperty(AddressStructureBean.PROP_CITY)));
//            addressStructure.setStae((PropertyChoiceValue) (addressStructure.getAddr().getProperty(AddressStructureBean.PROP_STAE)));
//            addressStructure.setPost((PropertyChoiceValue) (addressStructure.getAddr().getProperty(AddressStructureBean.PROP_POST)));
//            addressStructure.setCtry((PropertyChoiceValue) (addressStructure.getAddr().getProperty(AddressStructureBean.PROP_CTRY)));
//        }
//        addressStructure.setPhon((Property[]) (parentProperty.getProperties(AddressStructureBean.PROP_PHON)));
    }

    public void displayProperties() {
//            updateField(address_line, addressStructure.getAddr());
//            updateField(address_line1, addressStructure.getAddr1());
//            updateField(address_line2, addressStructure.getAddr2());
//            updateField(address_city, addressStructure.getCity());
//            updateField(address_state, addressStructure.getStae());
//            updateField(address_postal_code, addressStructure.getPost());
//            updateField(((JTextComponent) address_country.getEditor().getEditorComponent()), addressStructure.getCtry());
//            updateField(addressStructure.getPhon());
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
    }

    private void initEntitiesList() {
        Gedcom gedcom = parentProperty.getGedcom();
        List<Entity> tempList = new ArrayList<Entity>();
        tempList.add(null);
        tempList.addAll(Arrays.asList(gedcom.getEntities(Gedcom.OBJE, "OBJE:TITL")));
        mediaEntitiesList = tempList.toArray(new Entity[1]);
        xref_obje.setModel(new DefaultComboBoxModel(mediaEntitiesList));
    }

    private void initMediaList() {
        Property[] propList = parentProperty.getProperties("OBJE");
        List<MediaWrapper> mediaTmpList = new ArrayList<MediaWrapper>();
        for (int i = 0; i < propList.length; i++) {
            Property property = propList[i];
            mediaTmpList.add(new MediaWrapper(property));
        }
        mediaList = mediaTmpList.toArray(new MediaWrapper[1]);
        mediaListBox.setListData(mediaList);
        return;
    }

    private void displayMedia(Property selectedMedia) {
        if (busy) {
            return;
        }
        busy = true;
        if (selectedMedia instanceof PropertyXRef) {
            internalMediaButton.setSelected(true);
            PropertyXRef pRef = (PropertyXRef) selectedMedia;
            Entity entity = pRef.getTargetEntity();
            if (entity instanceof Media) {
                if (xref_obje.getSelectedItem() == (Media) entity) {
                    displayProperties((Property) entity);
                } else {
                    xref_obje.setSelectedItem((Media) entity);
                }
            }
        } else {
            externalMediaButton.setSelected(true);
            displayProperties(selectedMedia);
        }
        busy = false;
    }

    private void enableFields(boolean isInternal) {
        xref_obje.setEnabled(isInternal);
        if (!isInternal && !busy) {
            xref_obje.setSelectedIndex(0);
        }
        multimedia_file_reference.setEnabled(!isInternal);
        fileSearchButton.setEnabled(!isInternal);
        descriptive_title.setEditable(!isInternal);
        multimedia_format.setEditable(!isInternal);
    }

    private void displayProperties(Property selectedMedia) {
        if (selectedMedia == null) {
            return;
        }
        Property pTemp;
        pTemp = selectedMedia.getPropertyByPath("OBJE:TITL");
        descriptive_title.setText(pTemp != null ? pTemp.getDisplayValue() : "");
        pTemp = selectedMedia.getPropertyByPath("OBJE:FORM");
        multimedia_format.setText(pTemp != null ? pTemp.getDisplayValue() : "");
        pTemp = selectedMedia.getPropertyByPath("OBJE:FILE");
        multimedia_file_reference.setText(pTemp != null ? pTemp.getDisplayValue() : "");
        // afficher le media (image, son, video)
        mediaPanel.showMedia(mediaList[mediaListBox.getSelectedIndex()]);

    }

    /**
     * Class used to detect changes of field and commit gedcom changes for each valid modification
     */
    private class FieldInputVerifier extends InputVerifier {

        public FieldInputVerifier() {
            super();
        }

        @Override
        public boolean shouldYieldFocus(JComponent input) {
            boolean valid = verify(input);

            if (valid) {
                return true;
            } else {
                Toolkit.getDefaultToolkit().beep();
                return false;
            }
        }

        @Override
        public boolean verify(JComponent input) {
            JTextComponent jtc = (JTextComponent) input;
            String fieldText = jtc.getText();
//            if (jtc == address_line && hasFieldChanged(addressStructure.getAddr(), fieldText)) {
//                updateGedcom(parentProperty, addressStructure.getAddr(), AddressStructureBean.PROP_ADDR, fieldText);
//            }
            return true;
        }
    }
}
