/*
 * Ancestris - http://www.ancestris.org
 *
 * Copyright 2011 Ancestris
 *
 * Author: Daniel Andre (daniel@ancestris.org).
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */

package ancestris.modules.editors.standard;

import genj.app.Images;
import genj.gedcom.Context;
import genj.gedcom.Indi;
import genj.util.swing.Action2;
import genj.util.swing.Action2.Group;
import genj.view.ActionProvider;
import genj.view.SelectionListener;
import genjfr.app.AncestrisTopComponent;
import genjfr.app.GenjViewInterface;
import java.awt.Image;
import java.awt.event.ActionEvent;
import org.openide.util.lookup.ServiceProvider;

/**
 * Top component which displays something.
 */
//@ConvertAsProperties(dtd = "-//genjfr.app//Edit//EN",autostore = false)
@ServiceProvider(service = GenjViewInterface.class)
public final class EditTopComponent extends AncestrisTopComponent implements ActionProvider, SelectionListener {

    private static final String PREFERRED_ID = "EditTopComponent";
    private static EditTopComponent factory;
    FamilyPanel familyPanel = new FamilyPanel();
    GedcomPanel gedcomPanel = new GedcomPanel();

    @Override
    public boolean createPanel() {
        return true;
    }

    public String getDefaultFactoryMode() {
        return "genjfr-editor";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized EditTopComponent getFactory() {
        if (factory == null) {
            factory = new EditTopComponent();
        }
        return factory;
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    public void createActions(Context context, Purpose purpose, Group into) {
        if (purpose == Purpose.CONTEXT) {
            into.add(new OpenInEditor(context));
        }
    }

    @Override
    public Image getImageIcon() {
        return ResourcesSupport.icon.getImage();
    }


    @Override
    public void setContext(Context context) {
        super.setContext(context);
        setContext(context, true);
    }

    public void setContext(Context context, boolean isActionPerformed) {
        if (context == null) {
            return;
        }
        if (context.getEntity() != null && !context.getEntities().isEmpty()) {
            setPanel(familyPanel);
            familyPanel.setContext(context);
            return;
        }
        // Default to gedcom
        gedcomPanel.setContext(context);
        setPanel(gedcomPanel);
        repaint();
    }

    private class OpenInEditor extends Action2 {

        Context context;

        public OpenInEditor(Context context) {
            this.context = context;
            setText(ResourcesSupport.getTitle("OpenInEditor"));
            setImage(ResourcesSupport.icon);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            setContext(context);
        }
    }
}
