package ancestris.modules.editors.genealogyeditor.panels;

import genj.gedcom.Property;
import javax.swing.InputMap;
import javax.swing.KeyStroke;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultEditorKit;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.openide.util.ChangeSupport;

/**
 *
 * @author dominique
 */

/*
 * ADDRESS_STRUCTURE
 * n ADDR <ADDRESS_LINE>
 * +1 CONT <ADDRESS_LINE>
 * +1 ADR1 <ADDRESS_LINE1>
 * +1 ADR2 <ADDRESS_LINE2>
 * +1 ADR3 <ADDRESS_LINE3>
 * +1 CITY <ADDRESS_CITY>
 * +1 STAE <ADDRESS_STATE>
 * +1 POST <ADDRESS_POSTAL_CODE>
 * +1 CTRY <ADDRESS_COUNTRY>
 * n PHON <PHONE_NUMBER>
 * n EMAIL <ADDRESS_EMAIL>
 * n FAX <ADDRESS_FAX>
 * n WWW <ADDRESS_WEB_PAGE>
 */
public class AddressEditorPanel extends javax.swing.JPanel {

    private Property mRoot = null;
    private Property mAddress = null;
    private boolean mAddressModified = false;
    private boolean mAddrLineModified = false;
    private boolean mAddrLine1Modified = false;
    private boolean mAddrLine2Modified = false;
    private boolean mAddrLine3Modified = false;
    private boolean mCityModified = false;
    private boolean mStateModified = false;
    private boolean mPostalCodeModified = false;
    private boolean mCountryModified = false;
    private boolean mPhoneModified = false;
    private boolean mFaxModified = false;
    private boolean meMailAddrModified = false;
    private boolean mHttpAddrModified = false;
    private final ChangeListner changeListner = new ChangeListner();
    private final ChangeSupport changeSupport = new ChangeSupport(AddressEditorPanel.class);

    /**
     * Creates new form AddressEditorPanel
     */
    public AddressEditorPanel() {
        initComponents();
        AddrLineTextField.getDocument().addDocumentListener(changeListner);
        AddrLineTextField.getDocument().putProperty("name", "AddrLineTextField");

        addrLine1TextField.getDocument().addDocumentListener(changeListner);
        addrLine1TextField.getDocument().putProperty("name", "addrLine1TextField");

        addrLine2TextField.getDocument().addDocumentListener(changeListner);
        addrLine2TextField.getDocument().putProperty("name", "addrLine2TextField");

        addrLine3TextField.getDocument().addDocumentListener(changeListner);
        addrLine3TextField.getDocument().putProperty("name", "addrLine3TextField");

        cityTextField.getDocument().addDocumentListener(changeListner);
        cityTextField.getDocument().putProperty("name", "cityTextField");

        postalCodeTextField.getDocument().addDocumentListener(changeListner);
        postalCodeTextField.getDocument().putProperty("name", "postalCodeTextField");

        stateTextField.getDocument().addDocumentListener(changeListner);
        stateTextField.getDocument().putProperty("name", "stateTextField");

        countryTextField.getDocument().addDocumentListener(changeListner);
        countryTextField.getDocument().putProperty("name", "countryTextField");

        phoneTextField.getDocument().addDocumentListener(changeListner);
        phoneTextField.getDocument().putProperty("name", "phoneTextField");

        faxTextField.getDocument().addDocumentListener(changeListner);
        faxTextField.getDocument().putProperty("name", "faxTextField");

        httpAddrTextField.getDocument().addDocumentListener(changeListner);
        httpAddrTextField.getDocument().putProperty("name", "httpAddrTextField");

        eMailAddrTextField.getDocument().addDocumentListener(changeListner);
        eMailAddrTextField.getDocument().putProperty("name", "eMailAddrTextField");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        addrLine2TextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        addrLine3TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        eMailAddrTextField = new javax.swing.JTextField();
        eMailAddrLabel = new javax.swing.JLabel();
        httpAddrTextField = new javax.swing.JTextField();
        postalCodeTextField = new javax.swing.JTextField();
        httpAddrLabel = new javax.swing.JLabel();
        addrLine1TextField = new javax.swing.JTextField();
        postalCodeLabel = new javax.swing.JLabel();
        faxTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        faxLabel = new javax.swing.JLabel();
        AddrLineTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();

        phoneLabel.setText(org.openide.util.NbBundle.getMessage(AddressEditorPanel.class, "AddressEditorPanel.phoneLabel.text")); // NOI18N

        cityLabel.setText(org.openide.util.NbBundle.getMessage(AddressEditorPanel.class, "AddressEditorPanel.cityLabel.text")); // NOI18N

        countryLabel.setText(org.openide.util.NbBundle.getMessage(AddressEditorPanel.class, "AddressEditorPanel.countryLabel.text")); // NOI18N

        eMailAddrLabel.setText(org.openide.util.NbBundle.getMessage(AddressEditorPanel.class, "AddressEditorPanel.eMailAddrLabel.text")); // NOI18N

        httpAddrLabel.setText(org.openide.util.NbBundle.getMessage(AddressEditorPanel.class, "AddressEditorPanel.httpAddrLabel.text")); // NOI18N

        postalCodeLabel.setText(org.openide.util.NbBundle.getMessage(AddressEditorPanel.class, "AddressEditorPanel.postalCodeLabel.text")); // NOI18N

        faxLabel.setText(org.openide.util.NbBundle.getMessage(AddressEditorPanel.class, "AddressEditorPanel.faxLabel.text")); // NOI18N

        stateLabel.setText(org.openide.util.NbBundle.getMessage(AddressEditorPanel.class, "AddressEditorPanel.stateLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(httpAddrLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phoneLabel)
                        .addComponent(stateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addrLine1TextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addrLine2TextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addrLine3TextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddrLineTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityTextField)
                            .addComponent(stateTextField)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(httpAddrTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postalCodeLabel)
                            .addComponent(countryLabel)
                            .addComponent(faxLabel)
                            .addComponent(eMailAddrLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(faxTextField)
                            .addComponent(countryTextField)
                            .addComponent(postalCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(eMailAddrTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddrLineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addrLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addrLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addrLine3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeLabel)
                    .addComponent(postalCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryLabel)
                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faxLabel)
                    .addComponent(faxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(httpAddrLabel)
                    .addComponent(httpAddrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMailAddrLabel)
                    .addComponent(eMailAddrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddrLineTextField;
    private javax.swing.JTextField addrLine1TextField;
    private javax.swing.JTextField addrLine2TextField;
    private javax.swing.JTextField addrLine3TextField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JLabel eMailAddrLabel;
    private javax.swing.JTextField eMailAddrTextField;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JTextField faxTextField;
    private javax.swing.JLabel httpAddrLabel;
    private javax.swing.JTextField httpAddrTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JTextField postalCodeTextField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    // End of variables declaration//GEN-END:variables
    /**
     * Listener
     */
    public void addChangeListener(ChangeListener l) {
        changeSupport.addChangeListener(l);
    }

    /**
     * Listener
     */
    public void removeChangeListener(ChangeListener l) {
        changeSupport.removeChangeListener(l);
    }

    /**
     * @param root the parent property
     *
     * n ADDR <ADDRESS_LINE>
     * +1 CONT <ADDRESS_LINE>
     * +1 ADR1 <ADDRESS_LINE1>
     * +1 ADR2 <ADDRESS_LINE2>
     * +1 ADR3 <ADDRESS_LINE3>
     * +1 CITY <ADDRESS_CITY>
     * +1 STAE <ADDRESS_STATE>
     * +1 POST <ADDRESS_POSTAL_CODE>
     * +1 CTRY <ADDRESS_COUNTRY>
     * n PHON <PHONE_NUMBER>
     * n EMAIL <ADDRESS_EMAIL>
     * n FAX <ADDRESS_FAX>
     * n WWW <ADDRESS_WEB_PAGE>
     */
    public void set(Property root, Property address) {
        mAddress = address;
        mRoot = root;
        changeListner.mute();
        AutoCompleteDecorator.decorate((javax.swing.JTextField) cityTextField, mRoot.getGedcom().getReferenceSet("CITY").getKeys(), false);
        InputMap map = cityTextField.getInputMap();
        map.put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0), DefaultEditorKit.deletePrevCharAction);

        AutoCompleteDecorator.decorate((javax.swing.JTextField) stateTextField, mRoot.getGedcom().getReferenceSet("STAE").getKeys(), false);
        map = stateTextField.getInputMap();
        map.put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0), DefaultEditorKit.deletePrevCharAction);

        AutoCompleteDecorator.decorate((javax.swing.JTextField) postalCodeTextField, mRoot.getGedcom().getReferenceSet("POST").getKeys(), false);
        map = postalCodeTextField.getInputMap();
        map.put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0), DefaultEditorKit.deletePrevCharAction);

        AutoCompleteDecorator.decorate((javax.swing.JTextField) countryTextField, mRoot.getGedcom().getReferenceSet("CTRY").getKeys(), false);
        map = countryTextField.getInputMap();
        map.put(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0), DefaultEditorKit.deletePrevCharAction);

        if (mAddress != null) {
            AddrLineTextField.setText(address.getValue());
            Property propertyAdr1 = mAddress.getProperty("ADR1");
            addrLine1TextField.setText(propertyAdr1 != null ? propertyAdr1.getValue() : "");

            Property propertyAdr2 = mAddress.getProperty("ADR2");
            addrLine2TextField.setText(propertyAdr2 != null ? propertyAdr2.getValue() : "");

            Property propertyAdr3 = mAddress.getProperty("ADR3");
            addrLine3TextField.setText(propertyAdr3 != null ? propertyAdr3.getValue() : "");

            Property propertyCity = mAddress.getProperty("CITY");
            cityTextField.setText(propertyCity != null ? propertyCity.getValue() : "");

            Property propertyState = mAddress.getProperty("STAE");
            stateTextField.setText(propertyState != null ? propertyState.getValue() : "");

            Property propertyPostalCode = mAddress.getProperty("POST");
            postalCodeTextField.setText(propertyPostalCode != null ? propertyPostalCode.getValue() : "");

            Property propertyCountry = mAddress.getProperty("CTRY");
            countryTextField.setText(propertyCountry != null ? propertyCountry.getValue() : "");
        }

        Property propertyPhone;
        propertyPhone = mRoot.getProperty("PHON");
        phoneTextField.setText(propertyPhone != null ? propertyPhone.getValue() : "");

        Property propertyFax;
        if (mRoot.getGedcom().getGrammar().getVersion().equals("5.5.1")) {
            propertyFax = mRoot.getProperty("FAX");
        } else {
            propertyFax = mRoot.getProperty("_FAX");
        }
        faxTextField.setText(propertyFax != null ? propertyFax.getValue() : "");

        Property propertyeMailAddr;
        if (mRoot.getGedcom().getGrammar().getVersion().equals("5.5.1")) {

            propertyeMailAddr = mRoot.getProperty("EMAIL");
        } else {
            propertyeMailAddr = mRoot.getProperty("_EMAIL");
        }
        eMailAddrTextField.setText(propertyeMailAddr != null ? propertyeMailAddr.getValue() : "");

        Property propertyhttpAddr;
        if (mRoot.getGedcom().getGrammar().getVersion().equals("5.5.1")) {
            propertyhttpAddr = mRoot.getProperty("WWW");
        } else {
            propertyhttpAddr = mRoot.getProperty("_WWW");
        }
        httpAddrTextField.setText(propertyhttpAddr != null ? propertyhttpAddr.getValue() : "");

        changeListner.unmute();
    }

    public void commit() {
        if (mAddressModified) {
            mAddressModified = false;
            if (mAddress == null) {
                mAddress = mRoot.addProperty("ADDR", AddrLineTextField.getText());
            } else {
                if (mAddrLineModified) {
                    mAddress.setValue(AddrLineTextField.getText());
                }
            }

            if (mAddrLine1Modified) {
                mAddrLine1Modified = false;
                Property propertyAdr1 = mAddress.getProperty("ADR1");
                if (propertyAdr1 == null) {
                    mAddress.addProperty("ADR1", addrLine1TextField.getText());
                } else {
                    propertyAdr1.setValue(addrLine1TextField.getText());
                }
            }

            if (mAddrLine2Modified) {
                mAddrLine2Modified = false;
                Property propertyAdr2 = mAddress.getProperty("ADR2");
                if (propertyAdr2 == null) {
                    mAddress.addProperty("ADR2", addrLine2TextField.getText());
                } else {
                    propertyAdr2.setValue(addrLine2TextField.getText());
                }
            }

            if (mAddrLine3Modified) {
                mAddrLine3Modified = false;
                Property propertyAdr3 = mAddress.getProperty("ADR3");
                if (propertyAdr3 == null) {
                    mAddress.addProperty("ADR3", addrLine3TextField.getText());
                } else {
                    propertyAdr3.setValue(addrLine3TextField.getText());
                }
            }

            if (mCityModified) {
                mCityModified = false;
                Property propertyCity = mAddress.getProperty("CITY");
                if (propertyCity == null) {
                    mAddress.addProperty("CITY", cityTextField.getText());
                } else {
                    propertyCity.setValue(cityTextField.getText());
                }
            }

            if (mStateModified) {
                mStateModified = false;
                Property propertyState = mAddress.getProperty("STAE");
                if (propertyState == null) {
                    mAddress.addProperty("STAE", stateTextField.getText());
                } else {
                    propertyState.setValue(stateTextField.getText());
                }
            }

            if (mPostalCodeModified) {
                mPostalCodeModified = false;
                Property propertyPostalCode = mAddress.getProperty("POST");
                if (propertyPostalCode == null) {
                    mAddress.addProperty("POST", postalCodeTextField.getText());
                } else {
                    propertyPostalCode.setValue(postalCodeTextField.getText());
                }
            }

            if (mCountryModified) {
                mCountryModified = false;
                Property propertyCountry = mAddress.getProperty("CTRY");
                if (propertyCountry == null) {
                    mAddress.addProperty("CTRY", countryTextField.getText());
                } else {
                    propertyCountry.setValue(countryTextField.getText());
                }
            }
        }

        if (mPhoneModified) {
            mPhoneModified = false;
            Property propertyPhone = mRoot.getProperty("PHON");
            if (propertyPhone == null) {
                mRoot.addProperty("PHON", phoneTextField.getText());
            } else {
                propertyPhone.setValue(phoneTextField.getText());
            }
        }

        if (mFaxModified) {
            mFaxModified = false;
            if (mRoot.getGedcom().getGrammar().getVersion().equals("5.5.1")) {
                Property propertyFax = mRoot.getProperty("FAX");
                if (propertyFax == null) {
                    mRoot.addProperty("FAX", faxTextField.getText());
                } else {
                    propertyFax.setValue(faxTextField.getText());
                }
            } else {
                Property propertyFax = mRoot.getProperty("_FAX");
                if (propertyFax == null) {
                    mRoot.addProperty("_FAX", faxTextField.getText());
                } else {
                    propertyFax.setValue(faxTextField.getText());
                }
            }
        }

        if (meMailAddrModified) {
            meMailAddrModified = false;
            if (mRoot.getGedcom().getGrammar().getVersion().equals("5.5.1")) {
                Property propertyeMailAddr = mRoot.getProperty("EMAIL");
                if (propertyeMailAddr == null) {
                    mRoot.addProperty("EMAIL", eMailAddrTextField.getText());
                } else {
                    propertyeMailAddr.setValue(eMailAddrTextField.getText());
                }
            } else {
                Property propertyeMailAddr = mRoot.getProperty("_EMAIL");
                if (propertyeMailAddr == null) {
                    mRoot.addProperty("_EMAIL", eMailAddrTextField.getText());
                } else {
                    propertyeMailAddr.setValue(eMailAddrTextField.getText());
                }
            }
        }

        if (mHttpAddrModified) {
            mHttpAddrModified = false;
            if (mRoot.getGedcom().getGrammar().getVersion().equals("5.5.1")) {
                Property propertyhttpAddr = mRoot.getProperty("WWW");
                if (propertyhttpAddr == null) {
                    mRoot.addProperty("WWW", httpAddrTextField.getText());
                } else {
                    propertyhttpAddr.setValue(httpAddrTextField.getText());
                }
            } else {
                Property propertyhttpAddr = mRoot.getProperty("_WWW");
                if (propertyhttpAddr == null) {
                    mRoot.addProperty("_WWW", httpAddrTextField.getText());
                } else {
                    propertyhttpAddr.setValue(httpAddrTextField.getText());
                }
            }
        }
    }

    public class ChangeListner implements DocumentListener {

        private boolean mute = false;

        @Override
        public void insertUpdate(DocumentEvent de) {
            if (!mute) {
                mAddressModified = true;

                Object propertyName = de.getDocument().getProperty("name");
                if (propertyName != null) {
                    if (propertyName.equals("AddrLineTextField")) {
                        mAddrLineModified = true;
                    }
                    if (propertyName.equals("addrLine1TextField")) {
                        mAddrLine1Modified = true;
                    }
                    if (propertyName.equals("addrLine2TextField")) {
                        mAddrLine2Modified = true;
                    }
                    if (propertyName.equals("addrLine3TextField")) {
                        mAddrLine3Modified = true;
                    }
                    if (propertyName.equals("cityTextField")) {
                        mCityModified = true;
                    }
                    if (propertyName.equals("postalCodeTextField")) {
                        mStateModified = true;
                    }
                    if (propertyName.equals("stateTextField")) {
                        mPostalCodeModified = true;
                    }
                    if (propertyName.equals("countryTextField")) {
                        mCountryModified = true;
                    }
                    if (propertyName.equals("phoneTextField")) {
                        mPhoneModified = true;
                    }
                    if (propertyName.equals("faxTextField")) {
                        mFaxModified = true;
                    }
                    if (propertyName.equals("httpAddrTextField")) {
                        meMailAddrModified = true;
                    }
                    if (propertyName.equals("eMailAddrTextField")) {
                        mHttpAddrModified = true;
                    }

                    changeSupport.fireChange();
                }
            }
        }

        @Override
        public void removeUpdate(DocumentEvent de) {
            if (!mute) {
                mAddressModified = true;

                Object propertyName = de.getDocument().getProperty("name");
                if (propertyName != null) {
                    if (propertyName.equals("AddrLineTextField")) {
                        mAddrLineModified = true;
                    }
                    if (propertyName.equals("addrLine1TextField")) {
                        mAddrLine1Modified = true;
                    }
                    if (propertyName.equals("addrLine2TextField")) {
                        mAddrLine2Modified = true;
                    }
                    if (propertyName.equals("addrLine3TextField")) {
                        mAddrLine3Modified = true;
                    }
                    if (propertyName.equals("cityTextField")) {
                        mCityModified = true;
                    }
                    if (propertyName.equals("postalCodeTextField")) {
                        mStateModified = true;
                    }
                    if (propertyName.equals("stateTextField")) {
                        mPostalCodeModified = true;
                    }
                    if (propertyName.equals("countryTextField")) {
                        mCountryModified = true;
                    }
                    if (propertyName.equals("phoneTextField")) {
                        mPhoneModified = true;
                    }
                    if (propertyName.equals("faxTextField")) {
                        mFaxModified = true;
                    }
                    if (propertyName.equals("httpAddrTextField")) {
                        meMailAddrModified = true;
                    }
                    if (propertyName.equals("eMailAddrTextField")) {
                        mHttpAddrModified = true;
                    }

                    changeSupport.fireChange();
                }
            }
        }

        @Override
        public void changedUpdate(DocumentEvent de) {
            if (!mute) {
                mAddressModified = true;

                Object propertyName = de.getDocument().getProperty("name");
                if (propertyName != null) {
                    if (propertyName.equals("AddrLineTextField")) {
                        mAddrLineModified = true;
                    }
                    if (propertyName.equals("addrLine1TextField")) {
                        mAddrLine1Modified = true;
                    }
                    if (propertyName.equals("addrLine2TextField")) {
                        mAddrLine2Modified = true;
                    }
                    if (propertyName.equals("addrLine3TextField")) {
                        mAddrLine3Modified = true;
                    }
                    if (propertyName.equals("cityTextField")) {
                        mCityModified = true;
                    }
                    if (propertyName.equals("postalCodeTextField")) {
                        mStateModified = true;
                    }
                    if (propertyName.equals("stateTextField")) {
                        mPostalCodeModified = true;
                    }
                    if (propertyName.equals("countryTextField")) {
                        mCountryModified = true;
                    }
                    if (propertyName.equals("phoneTextField")) {
                        mPhoneModified = true;
                    }
                    if (propertyName.equals("faxTextField")) {
                        mFaxModified = true;
                    }
                    if (propertyName.equals("httpAddrTextField")) {
                        meMailAddrModified = true;
                    }
                    if (propertyName.equals("eMailAddrTextField")) {
                        mHttpAddrModified = true;
                    }

                    changeSupport.fireChange();
                }
            }
        }

        public void mute() {
            mute = true;
        }

        public void unmute() {
            mute = false;
        }
    }
}
