/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeoPlaceEditor.java
 *
 * Created on 2 avr. 2010, 22:28:09
 */
package genjfr.app.geo;

import genj.gedcom.Gedcom;
import genj.gedcom.GedcomException;
import genj.gedcom.PropertyPlace;
import genj.gedcom.UnitOfWork;
import genjfr.app.App;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.FlavorEvent;
import java.awt.datatransfer.FlavorListener;
import java.util.ArrayList;
import java.util.List;
import java.util.prefs.PreferenceChangeEvent;
import java.util.prefs.PreferenceChangeListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.geonames.InsufficientStyleException;
import org.geonames.Toponym;
import org.jdesktop.swingx.mapviewer.GeoPosition;
import org.netbeans.api.javahelp.Help;
import org.netbeans.api.options.OptionsDisplayer;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.StatusDisplayer;
import org.openide.util.Exceptions;
import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.util.NbPreferences;
import org.openide.util.datatransfer.ExClipboard;
import org.openide.windows.WindowManager;

/**
 *
 * @author frederic
 */
public class GeoPlaceEditor extends javax.swing.JPanel implements PreferenceChangeListener, FlavorListener {

    private GeoNodeObject geoObj = null;
    private List<Toponym> list = new ArrayList<Toponym>();
    private boolean isBusy = false;

    /** Creates new form GeoPlaceEditor */
    public GeoPlaceEditor(GeoNodeObject geoObj) {
        this.geoObj = geoObj;
        initComponents();
        enableAddressFields();
        jTextField1.setText(geoObj.getCity());
        fillPlaceFromGeoNode(geoObj);
        jLabel14.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jLabel18.setText("");
        jLabel19.setText("");
        jLabel20.setText("");
        jLabel21.setText("");
        jLabel34.setText("");
        jCheckBox1.setSelected(false);
        getClipboard().addFlavorListener(this);
        jButton4.setEnabled(getClipboard().isDataFlavorAvailable(GeoToken.geoPosFlavor));
        WindowManager.getDefault().invokeWhenUIReady(new Runnable() {

            public void run() {
                jButton1.doClick();
                jCheckBox1.doClick();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton5.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton5.text")); // NOI18N
        jButton5.setToolTipText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton5.toolTipText")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel27.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel27.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel11.text")); // NOI18N

        jLabel28.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel28.text")); // NOI18N

        jLabel25.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel25.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel9.text")); // NOI18N

        jLabel26.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel26.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel10.text")); // NOI18N

        jLabel30.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel30.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel7.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel8.text")); // NOI18N

        jLabel29.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel29.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel6.text")); // NOI18N

        jLabel32.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel32.text")); // NOI18N

        jLabel31.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel31.text")); // NOI18N

        jLabel14.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel14.text")); // NOI18N

        jLabel15.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel15.text")); // NOI18N

        jLabel16.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel16.text")); // NOI18N

        jLabel18.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel18.text")); // NOI18N

        jLabel19.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel19.text")); // NOI18N

        jLabel20.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel20.text")); // NOI18N

        jLabel21.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel21.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel1.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel4.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel2.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel2.text")); // NOI18N

        jLabel24.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel24.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel24.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton1.text")); // NOI18N
        jButton1.setToolTipText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton1.toolTipText")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField1.text")); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton2.text")); // NOI18N
        jButton2.setToolTipText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton2.toolTipText")); // NOI18N
        jButton2.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 29));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 29));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel3.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel3.text")); // NOI18N

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField2.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField2.text")); // NOI18N

        jTextField3.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField3.text")); // NOI18N

        jTextField4.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField4.text")); // NOI18N

        jTextField6.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField6.text")); // NOI18N

        jTextField7.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField7.text")); // NOI18N

        jTextField8.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField8.text")); // NOI18N

        jTextField9.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField9.text")); // NOI18N

        jLabel33.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel33.text")); // NOI18N

        jLabel34.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel34.text")); // NOI18N

        jLabel35.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jLabel35.text")); // NOI18N

        jTextField5.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField5.text")); // NOI18N

        jTextField10.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jTextField10.text")); // NOI18N

        jCheckBox1.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jCheckBox1.text")); // NOI18N
        jCheckBox1.setToolTipText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jCheckBox1.toolTipText")); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton3.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton3.text")); // NOI18N
        jButton3.setToolTipText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton3.toolTipText")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton4.text")); // NOI18N
        jButton4.setToolTipText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton4.toolTipText")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText(org.openide.util.NbBundle.getMessage(GeoPlaceEditor.class, "GeoPlaceEditor.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel25)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel26))
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel24)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel25)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14)
                            .addComponent(jLabel26)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel27)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16)
                            .addComponent(jLabel28)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel18)
                            .addComponent(jLabel29)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19)
                            .addComponent(jLabel30)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20)
                            .addComponent(jLabel31)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel21)
                            .addComponent(jLabel32)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton3)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(jButton6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        isBusy = true;
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        list = geoObj.getToponymsFromPlace(jTextField1.getText(), 30);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        if (list == null) {
            String msg = NbBundle.getMessage(GeoInternetSearch.class, "ERROR_cannotFindPlace");
            JOptionPane.showMessageDialog(WindowManager.getDefault().getMainWindow(), msg, NbBundle.getMessage(GeoInternetSearch.class, "ERROR_Title"), JOptionPane.ERROR_MESSAGE);
            StatusDisplayer.getDefault().setStatusText(msg, StatusDisplayer.IMPORTANCE_ANNOTATION * 10);
            System.out.println(msg);
            return;
        }
        jList1.setListData(list.toArray());
        isBusy = false;
        if (!list.isEmpty()) {
            jList1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (isBusy) {
            return;
        }
        Toponym topo = (Toponym) jList1.getSelectedValue();
        try {
            jLabel14.setText(topo.getName());
            jLabel15.setText(topo.getAdminCode4());
            jLabel16.setText(topo.getPostcode());
            jLabel18.setText(topo.getAdminName2());
            jLabel19.setText(topo.getAdminName1());
            jLabel20.setText(topo.getCountryName());
            jLabel21.setText(Double.toString(topo.getLatitude()));
            jLabel34.setText(Double.toString(topo.getLongitude()));
        } catch (InsufficientStyleException ex) {
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //jTextField6.setText("");
        jTextField7.setText(jLabel14.getText());
        jTextField8.setText(jLabel15.getText());
        jTextField9.setText(jLabel16.getText());
        jTextField2.setText(jLabel18.getText());
        jTextField3.setText(jLabel19.getText());
        jTextField4.setText(jLabel20.getText());
        jTextField5.setText(jLabel21.getText());
        jTextField10.setText(jLabel34.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OptionsDisplayer.getDefault().open("OptionsData");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        enableAddressFields();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (geoObj == null) {
            return;
        }
        JTextField placeFormat = new JTextField(geoObj.getGedcom().getPlaceFormat());
        String title = NbBundle.getMessage(GeoInternetSearch.class, "TXT_placeFormat") + " " + geoObj.getGedcom().getName();
        placeFormat.setPreferredSize(new Dimension(500, 30));
        NotifyDescriptor d = new NotifyDescriptor.Confirmation(placeFormat, title, NotifyDescriptor.OK_CANCEL_OPTION);
        if (DialogDisplayer.getDefault().notify(d) == NotifyDescriptor.OK_OPTION) {
            updateGedcomPlaceFormat(geoObj.getGedcom(), geoObj.getPlace(), placeFormat.getText());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Clipboard clipboard = getClipboard();
        try {
            GeoPosition geoPos = (GeoPosition) clipboard.getData(GeoToken.geoPosFlavor);
            if (geoPos != null) {
                jTextField5.setText(Double.toString(geoPos.getLatitude()));
                jTextField10.setText(Double.toString(geoPos.getLongitude()));
                return;
            }
            Toponym topo = (Toponym) clipboard.getData(GeoToken.topoFlavor);
            if (topo != null) {
                jTextField6.setText("");
                jTextField7.setText(topo.getName());
                jTextField8.setText(topo.getAdminCode4());
                jTextField9.setText(topo.getPostcode());
                jTextField2.setText(topo.getAdminName2());
                jTextField3.setText(topo.getAdminName1());
                jTextField4.setText(topo.getCountryName());
                jTextField5.setText(Double.toString(topo.getLatitude()));
                jTextField10.setText(Double.toString(topo.getLongitude()));
            }
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        getHelp();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void fillPlaceFromGeoNode(GeoNodeObject geoObj) {
        String str = "";
        str = NbPreferences.forModule(App.class).get("fmt_address1", "");
        jTextField6.setText((!str.equals("0") && isNumeric(str)) ? geoObj.getPlace().getJurisdiction(Integer.valueOf(str) - 1) : "");

        str = NbPreferences.forModule(App.class).get("fmt_address2", "");
        jTextField7.setText((!str.equals("0") && isNumeric(str)) ? geoObj.getPlace().getJurisdiction(Integer.valueOf(str) - 1) : "");

        str = NbPreferences.forModule(App.class).get("fmt_address3", "");
        jTextField8.setText((!str.equals("0") && isNumeric(str)) ? geoObj.getPlace().getJurisdiction(Integer.valueOf(str) - 1) : "");

        str = NbPreferences.forModule(App.class).get("fmt_address4", "");
        jTextField9.setText((!str.equals("0") && isNumeric(str)) ? geoObj.getPlace().getJurisdiction(Integer.valueOf(str) - 1) : "");

        str = NbPreferences.forModule(App.class).get("fmt_address5", "");
        jTextField2.setText((!str.equals("0") && isNumeric(str)) ? geoObj.getPlace().getJurisdiction(Integer.valueOf(str) - 1) : "");

        str = NbPreferences.forModule(App.class).get("fmt_address6", "");
        jTextField3.setText((!str.equals("0") && isNumeric(str)) ? geoObj.getPlace().getJurisdiction(Integer.valueOf(str) - 1) : "");

        str = NbPreferences.forModule(App.class).get("fmt_address7", "");
        jTextField4.setText((!str.equals("0") && isNumeric(str)) ? geoObj.getPlace().getJurisdiction(Integer.valueOf(str) - 1) : "");

        jTextField5.setText(Double.toString(geoObj.getLatitude()));
        jTextField10.setText(Double.toString(geoObj.getLongitude()));
    }

    public static boolean isNumeric(String inputData) {
        return inputData.matches("\\d+(.\\d+)?");
    }

    private void enableAddressFields() {
        jLabel25.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address1", "").equals("0") && !jCheckBox1.isSelected());
        jLabel26.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address2", "").equals("0") && !jCheckBox1.isSelected());
        jLabel27.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address3", "").equals("0") && !jCheckBox1.isSelected());
        jLabel28.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address4", "").equals("0") && !jCheckBox1.isSelected());
        jLabel29.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address5", "").equals("0") && !jCheckBox1.isSelected());
        jLabel30.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address6", "").equals("0") && !jCheckBox1.isSelected());
        jLabel31.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address7", "").equals("0") && !jCheckBox1.isSelected());

        jTextField6.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address1", "").equals("0") && !jCheckBox1.isSelected());
        jTextField7.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address2", "").equals("0") && !jCheckBox1.isSelected());
        jTextField8.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address3", "").equals("0") && !jCheckBox1.isSelected());
        jTextField9.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address4", "").equals("0") && !jCheckBox1.isSelected());
        jTextField2.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address5", "").equals("0") && !jCheckBox1.isSelected());
        jTextField3.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address6", "").equals("0") && !jCheckBox1.isSelected());
        jTextField4.setEnabled(!NbPreferences.forModule(App.class).get("fmt_address7", "").equals("0") && !jCheckBox1.isSelected());

        NbPreferences.forModule(App.class).addPreferenceChangeListener(this);
    }

    public void preferenceChange(PreferenceChangeEvent pce) {
        fillPlaceFromGeoNode(geoObj);
        enableAddressFields();
    }

    public void updateGedcom() {

        // if place to be updated, update gedcom
        Gedcom gedcom = geoObj.getPlace().getGedcom();
        if (!jCheckBox1.isSelected()) {
            final String place = buildPlaceStringFromFields();
            try {
                GeoPlacesList.getInstance(gedcom).stopListening();
                gedcom.doUnitOfWork(new UnitOfWork() {

                    public void perform(Gedcom gedcom) throws GedcomException {

                        // update all places in gedcom
                        List<PropertyPlace> propPlaces = geoObj.getEventsPlaces();
                        for (PropertyPlace pp : propPlaces) {
                            pp.setValue(place);
                        }

                        // remember for next time
                        Toponym topo = geoObj.getToponym();
                        updateTopoFromDialog(topo);
                        geoObj.setToponym(topo);
                        NbPreferences.forModule(GeoPlacesList.class).put(geoObj.getPlaceAsLongString(), geoObj.Toponym2Code(topo));

                        GeoPlacesList.getInstance(gedcom).refreshPlaceName();
                    }
                });
                GeoPlacesList.getInstance(gedcom).startListening();
            } catch (Exception e) {
                String msg = NbBundle.getMessage(GeoPlaceEditor.class, "ERROR_cannotUpdatePlace");
                JOptionPane.showMessageDialog(WindowManager.getDefault().getMainWindow(), msg, NbBundle.getMessage(GeoPlaceEditor.class, "ERROR_Title"), JOptionPane.ERROR_MESSAGE);
                System.out.println(msg + "\n" + e);
            }
            // else update only place locally: after a refresh, all places will be relocalised
        } else {
            Toponym topo = geoObj.getToponym();
            updateTopoFromDialog(topo);
            geoObj.setToponym(topo);
            NbPreferences.forModule(GeoPlacesList.class).put(geoObj.getPlaceAsLongString(), geoObj.Toponym2Code(topo));
            GeoPlacesList.getInstance(gedcom).refreshPlaceCoord();
        }


    }

    private void updateGedcomPlaceFormat(Gedcom gedcom, final PropertyPlace propPlace, final String text) {
        // form the origin
        try {
            GeoPlacesList.getInstance(gedcom).stopListening();
            gedcom.doUnitOfWork(new UnitOfWork() {

                public void perform(Gedcom gedcom) throws GedcomException {

                    // Create place format
                    //gedcom.setPlaceFormat(text);
                    propPlace.setFormatAsString(true, text);
                }
            });
            GeoPlacesList.getInstance(gedcom).startListening();
        } catch (Exception e) {
            String msg = NbBundle.getMessage(GeoPlaceEditor.class, "ERROR_cannotUpdatePlace");
            JOptionPane.showMessageDialog(WindowManager.getDefault().getMainWindow(), msg, NbBundle.getMessage(GeoPlaceEditor.class, "ERROR_Title"), JOptionPane.ERROR_MESSAGE);
            System.out.println(msg + "\n" + e);
        }

    }

    private void updateTopoFromDialog(Toponym topo) {

        try {
            topo.setName(jTextField7.getText());
            topo.setLatitude(Double.parseDouble(jTextField5.getText().trim().isEmpty() ? "45" : jTextField5.getText()));
            topo.setLongitude(Double.parseDouble(jTextField10.getText().trim().isEmpty() ? "-4" : jTextField10.getText()));
            topo.setCountryName(jTextField4.getText());
            topo.setAdminName2(jTextField2.getText());
            topo.setAdminName3(jTextField3.getText());
            topo.setAdminCode4(jTextField8.getText());
            topo.setPostcode(jTextField9.getText());
        } catch (Throwable t) {
        }
        return;
    }

    static public Clipboard getClipboard() {
        Clipboard c = Lookup.getDefault().lookup(ExClipboard.class);
        if (c == null) {
            c = java.awt.Toolkit.getDefaultToolkit().getSystemClipboard();
        }
        return c;
    }

    public void flavorsChanged(FlavorEvent fe) {
        jButton4.setEnabled(getClipboard().isDataFlavorAvailable(GeoToken.geoPosFlavor) || getClipboard().isDataFlavorAvailable(GeoToken.topoFlavor));
    }

    /**
     *
     * @return
     */
    private String buildPlaceStringFromFields() {
        String[] placeArray = new String[7];
        String ret = "";

        for (int i = 0; i < placeArray.length; i++) {
            placeArray[i] = "@f[*";  // any weird string the user will not write by chance in one of the fields
        }
        fillPlaceArray(placeArray, NbPreferences.forModule(App.class).get("fmt_address1", ""), jTextField6);
        fillPlaceArray(placeArray, NbPreferences.forModule(App.class).get("fmt_address2", ""), jTextField7);
        fillPlaceArray(placeArray, NbPreferences.forModule(App.class).get("fmt_address3", ""), jTextField8);
        fillPlaceArray(placeArray, NbPreferences.forModule(App.class).get("fmt_address4", ""), jTextField9);
        fillPlaceArray(placeArray, NbPreferences.forModule(App.class).get("fmt_address5", ""), jTextField2);
        fillPlaceArray(placeArray, NbPreferences.forModule(App.class).get("fmt_address6", ""), jTextField3);
        fillPlaceArray(placeArray, NbPreferences.forModule(App.class).get("fmt_address7", ""), jTextField4);

        for (int i = 0; i < placeArray.length; i++) {
            if (placeArray[i].equals("@f[*")) {
                break;
            }
            if (i > 0) {
                ret += "," + (NbPreferences.forModule(App.class).get("address_splitspaces", "").equals("true") ? " " : "");
            }
            ret += placeArray[i];
        }
        return ret;
    }

    private void fillPlaceArray(String[] placeArray, String str, JTextField jtf) {
        if (!str.equals("0") && isNumeric(str)) {
            placeArray[Integer.valueOf(str) - 1] = jtf.getText();
        }
    }

    public void getHelp() {
        String id = "ancestris.app.view.geo.editplace";
        Help help = Lookup.getDefault().lookup(Help.class);
        if (help != null && help.isValidID(id, true).booleanValue()) {
            help.showHelp(new HelpCtx(id));
        } else {
            //    Toolkit.getDefaultToolkit().beep();
        }
        return;
    }
}
