/*
 * Ancestris - http://www.ancestris.org
 * 
 * Copyright 2016 Ancestris
 * 
 * Author: Frédéric Lapeyre (frederic@ancestris.org).
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package ancestris.modules.editors.standard.tools;

import ancestris.modules.editors.standard.IndiPanel;
import genj.gedcom.Indi;
import genj.gedcom.PropertyName;
import javax.swing.JTextField;

/**
 *
 * 
 * PERSONAL_NAME_STRUCTURE: =  5.5
 * 
 *   n  NAME <NAME_PERSONAL>  {1:1}
 *     +1 NPFX <NAME_PIECE_PREFIX>  {0:1}                           <== used in this details panel     Dr.
 *     +1 GIVN <NAME_PIECE_GIVEN>  {0:1}                         ***<== Firstname (main panel)         Robert
 *     +1 SPFX <NAME_PIECE_SURNAME_PREFIX>  {0:1}                   <== used in this details panel     de la
 *     +1 SURN <NAME_PIECE_SURNAME>  {0:1}                       ***<== Lastname (main panel)          Taille
 *     +1 NSFX <NAME_PIECE_SUFFIX>  {0:1}                           <== used in this details panel     Junior
 *     +1 NICK <NAME_PIECE_NICKNAME>  {0:1}                         <== used in this details panel     Bob
 *     +1 <<SOURCE_CITATION>>  {0:M}
 *       +2 <<NOTE_STRUCTURE>>  {0:M}
 *       +2 <<MULTIMEDIA_LINK>>  {0:M}
 *     +1 <<NOTE_STRUCTURE>>  {0:M}
 * 
 * 
 * PERSONAL_NAME_STRUCTURE:  5.5.1                              <== only use what we have in 5.5
 *   n NAME <NAME_PERSONAL>     {1:1}
 *   +1 TYPE <NAME_TYPE>    {0:1}
 *   +1 <<PERSONAL_NAME_PIECES>>    {0:1}
 *      NPFX <NAME_PIECE_PREFIX>   {0:1}
 *      GIVN <NAME_PIECE_GIVEN>   {0:1}
 *      SPFX <NAME_PIECE_SURNAME_PREFIX>   {0:1}
 *      SURN <NAME_PIECE_SURNAME>   {0:1}
 *      NSFX <NAME_PIECE_SUFFIX>   {0:1}
 *      NICK <NAME_PIECE_NICKNAME>    {0:1}
 * 
 *   +1 FONE <NAME_PHONETIC_VARIATION>  {0:M}
 *      +2 TYPE <PHONETIC_TYPE>     {1:1}
 *      +2 <<PERSONAL_NAME_PIECES>>     {0:1}
 *      etc.
 *   +1 ROMN <NAME_ROMANIZED_VARIATION>     {0:M}
 *      +2 TYPE <ROMANIZED_TYPE>    {1:1}
 *      +2 <<PERSONAL_NAME_PIECES>>     {0:1}
 *      etc.
 * 
 * @author frederic
 */
public class NameDetailsPanel extends javax.swing.JPanel {

    private JTextField firstnamesText = null;
    private JTextField lastnamesText = null;
    private JTextField nicknamesText = null;

    
    /**
     * Creates new form NameDetailsPanel
     */
    public NameDetailsPanel() {
        initComponents();
        firstnamesText = (JTextField) firstnamesCombo.getEditor().getEditorComponent();
        lastnamesText = (JTextField) lastnamesCombo.getEditor().getEditorComponent();
        nicknamesText = (JTextField) nicknamesCombo.getEditor().getEditorComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        surnamePrefixText = new javax.swing.JTextField();
        exampleLabel = new javax.swing.JLabel();
        suffixText = new javax.swing.JTextField();
        exPrefix = new javax.swing.JLabel();
        exFirst = new javax.swing.JLabel();
        prefixLabel = new javax.swing.JLabel();
        exSurnPrefix = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        exSurname = new javax.swing.JLabel();
        surnamePrefixLabel = new javax.swing.JLabel();
        exSuffix = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        suffixLabel = new javax.swing.JLabel();
        nickLabel = new javax.swing.JLabel();
        prefixText = new javax.swing.JTextField();
        nicknamesCombo = new javax.swing.JComboBox();
        firstnamesCombo = new javax.swing.JComboBox();
        lastnamesCombo = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        surnamePrefixText.setText(org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.surnamePrefixText.text")); // NOI18N

        exampleLabel.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(exampleLabel, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.exampleLabel.text")); // NOI18N
        exampleLabel.setPreferredSize(new java.awt.Dimension(57, 18));

        suffixText.setText(org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.suffixText.text")); // NOI18N

        exPrefix.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(exPrefix, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.exPrefix.text")); // NOI18N
        exPrefix.setPreferredSize(new java.awt.Dimension(42, 18));

        exFirst.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(exFirst, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.exFirst.text")); // NOI18N
        exFirst.setPreferredSize(new java.awt.Dimension(95, 18));

        org.openide.awt.Mnemonics.setLocalizedText(prefixLabel, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.prefixLabel.text")); // NOI18N

        exSurnPrefix.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(exSurnPrefix, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.exSurnPrefix.text")); // NOI18N
        exSurnPrefix.setPreferredSize(new java.awt.Dimension(31, 18));

        org.openide.awt.Mnemonics.setLocalizedText(firstLabel, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.firstLabel.text")); // NOI18N

        exSurname.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(exSurname, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.exSurname.text")); // NOI18N
        exSurname.setPreferredSize(new java.awt.Dimension(39, 18));

        org.openide.awt.Mnemonics.setLocalizedText(surnamePrefixLabel, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.surnamePrefixLabel.text")); // NOI18N

        exSuffix.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(exSuffix, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.exSuffix.text")); // NOI18N
        exSuffix.setPreferredSize(new java.awt.Dimension(36, 18));

        org.openide.awt.Mnemonics.setLocalizedText(surnameLabel, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.surnameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(suffixLabel, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.suffixLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nickLabel, org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.nickLabel.text")); // NOI18N

        prefixText.setText(org.openide.util.NbBundle.getMessage(NameDetailsPanel.class, "NameDetailsPanel.prefixText.text")); // NOI18N
        prefixText.setPreferredSize(new java.awt.Dimension(50, 27));

        nicknamesCombo.setEditable(true);
        nicknamesCombo.setMaximumRowCount(19);

        firstnamesCombo.setEditable(true);
        firstnamesCombo.setMaximumRowCount(19);

        lastnamesCombo.setEditable(true);
        lastnamesCombo.setMaximumRowCount(19);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exampleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exPrefix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prefixText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prefixLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exSurnPrefix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(surnamePrefixText)
                    .addComponent(surnamePrefixLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exSuffix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suffixText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suffixLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(nickLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nicknamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixLabel)
                    .addComponent(firstLabel)
                    .addComponent(surnamePrefixLabel)
                    .addComponent(surnameLabel)
                    .addComponent(suffixLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnamePrefixText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suffixText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exSurnPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exampleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nickLabel)
                    .addComponent(nicknamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exFirst;
    private javax.swing.JLabel exPrefix;
    private javax.swing.JLabel exSuffix;
    private javax.swing.JLabel exSurnPrefix;
    private javax.swing.JLabel exSurname;
    private javax.swing.JLabel exampleLabel;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JComboBox firstnamesCombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox lastnamesCombo;
    private javax.swing.JLabel nickLabel;
    private javax.swing.JComboBox nicknamesCombo;
    private javax.swing.JLabel prefixLabel;
    private javax.swing.JTextField prefixText;
    private javax.swing.JLabel suffixLabel;
    private javax.swing.JTextField suffixText;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel surnamePrefixLabel;
    private javax.swing.JTextField surnamePrefixText;
    // End of variables declaration//GEN-END:variables

    public void setDetails(Indi indi) {
        PropertyName p = (PropertyName) indi.getProperty("NAME", true);
        if (p == null) {
            return;
        }
       
        AutoCompletion.reset(firstnamesCombo, PropertyName.getFirstNames(indi.getGedcom(), true));
        firstnamesText.setText(indi.getFirstName());

        AutoCompletion.reset(lastnamesCombo, PropertyName.getLastNames(indi.getGedcom(), true));
        lastnamesText.setText(indi.getLastName());

        prefixText.setText(p.getNamePrefix());
        surnamePrefixText.setText(p.getSurnamePrefix());
        suffixText.setText(p.getSuffix());

        AutoCompletion.reset(nicknamesCombo, PropertyName.getNickNames(indi.getGedcom(), true));
        nicknamesText.setText(p.getNick());
        
    }

    public void saveNameDetails(Indi indi, String first, String last) {
        PropertyName p = (PropertyName) indi.getProperty("NAME", true);
        if (p == null) {
            indi.setName(first, last);
            p = (PropertyName) indi.getProperty("NAME", true);
        }
        
        // Quit if nothing has changed
        if (p.getNamePrefix().equals(prefixText.getText())
         && p.getFirstName().equals(firstnamesText) 
         && p.getSurnamePrefix().equals(surnamePrefixText.getText())
         && p.getLastName().equals(lastnamesText)
         && p.getSuffix().equals(suffixText.getText())
         && p.getNick().equals(nicknamesText)) {
            return;
        }
        
        p.setName(prefixText.getText(), first, surnamePrefixText.getText(), last, suffixText.getText());
        p.setNick(nicknamesText.getText());
    }

    public void addListeners(IndiPanel panel) {
        firstnamesText.getDocument().addDocumentListener(panel);
        lastnamesText.getDocument().addDocumentListener(panel);
        prefixText.getDocument().addDocumentListener(panel);
        surnamePrefixText.getDocument().addDocumentListener(panel);
        suffixText.getDocument().addDocumentListener(panel);
        nicknamesText.getDocument().addDocumentListener(panel);
    }

    public String getFirstName() {
        return firstnamesText.getText();
    }

    public String getLastName() {
        return lastnamesText.getText();
    }
}
