#!/bin/bash
#


########################################################################
###                                                                  ###
###     S C R I P T   P O U R   F G E N J                            ###
###                                                                  ###
###                           (Derniere modification  15 avril 2009) ###
###                           [version 0.01]                         ###
########################################################################


### ---------------------------------------------------------------- ###
### Differentes variables - Changez les variables ci-dessous pour    ###
###                  faire correspondre ce script a votre systeme    ###
### ---------------------------------------------------------------- ###


# On commence par savoir qui on est et ou se site notre home directory
WHOAMI='whoami'
HOME_DIR="/home/$WHOAMI"
GENJ_DIR="$HOME_DIR/genj"

REPORTS_DIR="$HOME_DIR/svn/fgenj/dev/trunk/app/src/report"


cd `dirname $0`

clear

echo "/**"
echo " * Compilation de nos petits rapports bien francais"
echo " * "
echo " */"

JAR="$GENJ_DIR/lib/genj.jar"

LIB_ADDED_FOR_TOOLS_DIRECTORY="$GENJ_DIR/report/tools/tools.jar"
LIB_ADDED_FOR_REPORTS_DIRECTORY="$GENJ_DIR/report/ReportEditOptions.jar"
LIB_ADDED_FOR_GEDART_DIRECTORY="$GENJ_DIR/report/gedart/oro-2.0.8.jar:$GENJ_DIR/report/gedart/commons-lang-2.1.jar:$GENJ_DIR/report/gedart/commons-collections-3.1.jar:$GENJ_DIR/report/gedart/velocity-1.5.jar:$GENJ_DIR/report/gedart/stringtemplate.jar:$GENJ_DIR/report/gedart/velocity-tools-generic-1.3.jar"
LIB_ADDED_FOR_LIB_DIRECTORY="$GENJ_DIR/lib/junit.jar:$GENJ_DIR/lib/geo.jar:$GENJ_DIR/lib/jump.jar:$GENJ_DIR/lib/jfreechart.jar:$GENJ_DIR/lib/graphj.jar"
LIB_ADDED=$LIB_ADDED_FOR_TOOLS_DIRECTORY:$LIB_ADDED_FOR_REPORTS_DIRECTORY:$LIB_ADDED_FOR_GEDART_DIRECTORY:$LIB_ADDED_FOR_LIB_DIRECTORY

if [ -e "$JAR" ] ; then
#  CLASSPATH=.:$CLASSPATH:$JAR:$SWING
  CLASSPATH=.:$CLASSPATH:$JAR:$LIB_ADDED
else
#  CLASSPATH=.:$CLASSPATH:"../classes":$SWING
  CLASSPATH=.:$CLASSPATH:"../classes":$LIB_ADDED
fi

export CLASSPATH


if [[ $1 = "" ]] ; then
   echo "1 - Compilation des fichiers .java dans le repertoire racine de reports"
   javac -cp $GENJ_DIR/lib/genj.jar $REPORTS_DIR/tools/*.java $REPORTS_DIR/tools/imports/*.java
   exit 1
else
   $JAVA_HOME/bin/javac $1
fi

