#!/bin/bash
#


clear

echo "/**"
echo " * Compilation de nos petits rapports bien francais"
echo " * "
echo " */"

JAR="../lib/genj.jar"
# SWING="../lib/swing.jar"
# LIB_ADDED="../report/jfreechart-0.9.6.jar:../report/jcommon-0.7.2.jar:../report/gnujaxp.jar:../report/geotools.jar:../report/support.jar:../report/collections.jar"

LIB_ADDED_FOR_TOOLS_DIRECTORY="../report/tools/tools.jar"
LIB_ADDED_FOR_REPORTS_DIRECTORY="../report/ReportEditOptions.jar"
LIB_ADDED_FOR_GEDART_DIRECTORY="../report/gedart/oro-2.0.8.jar:../report/gedart/commons-lang-2.1.jar:../report/gedart/commons-collections-3.1.jar:../report/gedart/velocity-1.5.jar:../report/gedart/stringtemplate.jar:../report/gedart/velocity-tools-generic-1.3.jar"
LIB_ADDED_FOR_LIB_DIRECTORY="../lib/junit.jar:../lib/geo.jar:../lib/jump.jar:../lib/jfreechart.jar:../lib/graphj.jar"
LIB_ADDED=$LIB_ADDED_FOR_TOOLS_DIRECTORY:$LIB_ADDED_FOR_REPORTS_DIRECTORY:$LIB_ADDED_FOR_GEDART_DIRECTORY:$LIB_ADDED_FOR_LIB_DIRECTORY

if [ -e "$JAR" ] ; then
#  CLASSPATH=.:$CLASSPATH:$JAR:$SWING
  CLASSPATH=.:$CLASSPATH:$JAR:$LIB_ADDED
else
#  CLASSPATH=.:$CLASSPATH:"../classes":$SWING
  CLASSPATH=.:$CLASSPATH:"../classes":$LIB_ADDED
fi

export CLASSPATH


if [[ $1 = "" ]] ; then
   echo "1 - Compilation des fichiers .java dans le repertoire racine de reports"
   $JAVA_HOME/bin/javac *.java
   exit 1
else
   $JAVA_HOME/bin/javac $1
fi

