package ancestris.modules.editors.genealogyeditor.panels;

import ancestris.modules.editors.genealogyeditor.models.IndividualsTableModel;
import ancestris.util.swing.DialogManager;
import genj.gedcom.*;
import java.util.ArrayList;
import java.util.List;
import org.openide.DialogDescriptor;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;

/**
 *
 * @author dominique
 */
public class ChildrenListPanel extends javax.swing.JPanel {

    private IndividualsTableModel mIndividualsTableModel = new IndividualsTableModel();
    private Fam mRoot;
    private Indi mIndividual;

    /**
     * Creates new form IndividualsListPanel
     */
    public ChildrenListPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndividualsToolBar = new javax.swing.JToolBar();
        addChildrenButton = new javax.swing.JButton();
        editChildrenButton = new javax.swing.JButton();
        deleteChildrenButton = new javax.swing.JButton();
        linkToChildrenButton = new javax.swing.JButton();
        childrensScrollPane = new javax.swing.JScrollPane();
        individualsTable = new javax.swing.JTable();

        IndividualsToolBar.setFloatable(false);
        IndividualsToolBar.setRollover(true);

        addChildrenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ancestris/modules/editors/genealogyeditor/resources/edit_add.png"))); // NOI18N
        addChildrenButton.setToolTipText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("ChildrenListPanel.addChildrenButton.toolTipText"), new Object[] {})); // NOI18N
        addChildrenButton.setFocusable(false);
        addChildrenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addChildrenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addChildrenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChildrenButtonActionPerformed(evt);
            }
        });
        IndividualsToolBar.add(addChildrenButton);

        editChildrenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ancestris/modules/editors/genealogyeditor/resources/edit.png"))); // NOI18N
        editChildrenButton.setToolTipText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("ChildrenListPanel.editChildrenButton.toolTipText"), new Object[] {})); // NOI18N
        editChildrenButton.setFocusable(false);
        editChildrenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editChildrenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editChildrenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editChildrenButtonActionPerformed(evt);
            }
        });
        IndividualsToolBar.add(editChildrenButton);

        deleteChildrenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ancestris/modules/editors/genealogyeditor/resources/edit_delete.png"))); // NOI18N
        deleteChildrenButton.setToolTipText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("ChildrenListPanel.deleteChildrenButton.toolTipText"), new Object[] {})); // NOI18N
        deleteChildrenButton.setFocusable(false);
        deleteChildrenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteChildrenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteChildrenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteChildrenButtonActionPerformed(evt);
            }
        });
        IndividualsToolBar.add(deleteChildrenButton);

        linkToChildrenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ancestris/modules/editors/genealogyeditor/resources/link_add.png"))); // NOI18N
        linkToChildrenButton.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("ChildrenListPanel.linkToChildrenButton.text"), new Object[] {})); // NOI18N
        linkToChildrenButton.setToolTipText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("ChildrenListPanel.linkToChildrenButton.toolTipText"), new Object[] {})); // NOI18N
        linkToChildrenButton.setFocusable(false);
        linkToChildrenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linkToChildrenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linkToChildrenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkToChildrenButtonActionPerformed(evt);
            }
        });
        IndividualsToolBar.add(linkToChildrenButton);

        individualsTable.setModel(mIndividualsTableModel);
        individualsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                individualsTableMouseClicked(evt);
            }
        });
        childrensScrollPane.setViewportView(individualsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndividualsToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
            .addComponent(childrensScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IndividualsToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childrensScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addChildrenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChildrenButtonActionPerformed
        try {
            mRoot.getGedcom().doUnitOfWork(new UnitOfWork() {

                @Override
                public void perform(Gedcom gedcom) throws GedcomException {
                    mIndividual = (Indi) gedcom.createEntity(Gedcom.INDI);
                }
            }); // end of doUnitOfWork

        } catch (GedcomException ex) {
            Exceptions.printStackTrace(ex);
        } finally {
            IndividualEditorPanel individualEditorPanel = new IndividualEditorPanel();
            individualEditorPanel.set(mIndividual);

            DialogManager.ADialog individualEditorDialog = new DialogManager.ADialog(
                    NbBundle.getMessage(IndividualEditorPanel.class, "IndividualEditorPanel.title"),
                    individualEditorPanel);
            individualEditorDialog.setDialogId(IndividualEditorPanel.class.getName());

            if (individualEditorDialog.show() == DialogDescriptor.OK_OPTION) {
                mIndividualsTableModel.add(individualEditorPanel.commit());
            } else {
                mRoot.getGedcom().undoUnitOfWork(false);
            }
        }
    }//GEN-LAST:event_addChildrenButtonActionPerformed

    private void editChildrenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editChildrenButtonActionPerformed
        int rowIndex = individualsTable.convertRowIndexToModel(individualsTable.getSelectedRow());
        if (rowIndex != -1) {
            IndividualEditorPanel individualEditorPanel = new IndividualEditorPanel();
            individualEditorPanel.set(mIndividualsTableModel.getValueAt(rowIndex));

            DialogManager.ADialog individualEditorDialog = new DialogManager.ADialog(
                    NbBundle.getMessage(IndividualEditorPanel.class, "IndividualEditorPanel.title"),
                    individualEditorPanel);
            individualEditorDialog.setDialogId(IndividualEditorPanel.class.getName());

            if (individualEditorDialog.show() == DialogDescriptor.OK_OPTION) {
                individualEditorPanel.commit();
            }
        }
    }//GEN-LAST:event_editChildrenButtonActionPerformed

    private void deleteChildrenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteChildrenButtonActionPerformed
   }//GEN-LAST:event_deleteChildrenButtonActionPerformed

    private void individualsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_individualsTableMouseClicked
        if (evt.getClickCount() >= 2) {
            int rowIndex = individualsTable.convertRowIndexToModel(individualsTable.getSelectedRow());
            if (rowIndex != -1) {
                IndividualEditorPanel individualEditorPanel = new IndividualEditorPanel();
                individualEditorPanel.set(mIndividualsTableModel.getValueAt(rowIndex));

                DialogManager.ADialog individualEditorDialog = new DialogManager.ADialog(
                        NbBundle.getMessage(IndividualEditorPanel.class, "IndividualEditorPanel.title"),
                        individualEditorPanel);
                individualEditorDialog.setDialogId(IndividualEditorPanel.class.getName());

                if (individualEditorDialog.show() == DialogDescriptor.OK_OPTION) {
                    individualEditorPanel.commit();
                }
            }
        }
    }//GEN-LAST:event_individualsTableMouseClicked

    private void linkToChildrenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkToChildrenButtonActionPerformed
        IndividualsListPanel individualsListPanel = new IndividualsListPanel();
        List<Indi> individualsList = new ArrayList<Indi>(mRoot.getGedcom().getIndis());
        individualsListPanel.setIndividualsList(mRoot, individualsList);
        DialogManager.ADialog individualsListDialog = new DialogManager.ADialog(
                NbBundle.getMessage(IndividualsListPanel.class, "IndividualsListPanel.title.select.child"),
                individualsListPanel);
        individualsListDialog.setDialogId(IndividualsListPanel.class.getName());

        if (individualsListDialog.show() == DialogDescriptor.OK_OPTION) {
            mIndividualsTableModel.add(individualsListPanel.getSelectedIndividual());
        }
    }//GEN-LAST:event_linkToChildrenButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar IndividualsToolBar;
    private javax.swing.JButton addChildrenButton;
    private javax.swing.JScrollPane childrensScrollPane;
    private javax.swing.JButton deleteChildrenButton;
    private javax.swing.JButton editChildrenButton;
    private javax.swing.JTable individualsTable;
    private javax.swing.JButton linkToChildrenButton;
    // End of variables declaration//GEN-END:variables

    public void setChildrensList(Fam root, List<Indi> individualsList) {
        this.mRoot = root;
        mIndividualsTableModel.update(individualsList);
    }

    public Indi getSelectedChildren() {
        int selectedRow = individualsTable.getSelectedRow();
        if (selectedRow != -1) {
            int rowIndex = individualsTable.convertRowIndexToModel(selectedRow);
            return mIndividualsTableModel.getValueAt(rowIndex);
        } else {
            return null;
        }
    }

    public void commit() {
    }
}
