package ancestris.modules.editors.genealogyeditor.panels;

import ancestris.modules.editors.genealogyeditor.models.FamilyNamesTableModel;
import ancestris.modules.editors.genealogyeditor.models.NameTypeComboBoxModel;
import genj.gedcom.Property;
import genj.gedcom.PropertyName;

/**
 *
 * @author dominique
 */
public class NameEditorPanel extends javax.swing.JPanel {

    private NameTypeComboBoxModel nameTypeComboBoxModelModel = new NameTypeComboBoxModel();
    private FamilyNamesTableModel familyNamesTableModel = new FamilyNamesTableModel();
    private PropertyName nameToEdit = null;

    /**
     * Creates new form NameEditorPanel
     */
    public NameEditorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTypeLabel = new javax.swing.JLabel();
        nameTypeComboBox = new javax.swing.JComboBox<String>();
        firstNamePanel = new javax.swing.JPanel();
        firstNamePrefixLabel = new javax.swing.JLabel();
        firstNamePrefixTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        firstNameSufixLabel = new javax.swing.JLabel();
        firstNameSuffixTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nicknameTextField = new javax.swing.JTextField();
        familyNamesPanel = new javax.swing.JPanel();
        familyNamesToolBar = new javax.swing.JToolBar();
        addFamilyNameButton = new javax.swing.JButton();
        editFamilyNameButton = new javax.swing.JButton();
        deleteFamilyNameButton = new javax.swing.JButton();
        familyNamesScrollPane = new javax.swing.JScrollPane();
        familyNamesTable = new javax.swing.JTable();

        nameTypeLabel.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.nameTypeLabel.text"), new Object[] {})); // NOI18N

        nameTypeComboBox.setModel(nameTypeComboBoxModelModel);

        firstNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.firstNamePanel.border.title"), new Object[] {}), 1, 0, null, java.awt.Color.white)); // NOI18N

        firstNamePrefixLabel.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.firstNamePrefixLabel.text"), new Object[] {})); // NOI18N

        firstNamePrefixTextField.setColumns(8);

        firstNameLabel.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.firstNameLabel.text"), new Object[] {})); // NOI18N

        firstNameSufixLabel.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.firstNameSufixLabel.text"), new Object[] {})); // NOI18N

        firstNameSuffixTextField.setColumns(8);
        firstNameSuffixTextField.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.firstNameSuffixTextField.text"), new Object[] {})); // NOI18N

        jLabel1.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.jLabel1.text"), new Object[] {})); // NOI18N

        jLabel2.setText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.jLabel2.text"), new Object[] {})); // NOI18N

        javax.swing.GroupLayout firstNamePanelLayout = new javax.swing.GroupLayout(firstNamePanel);
        firstNamePanel.setLayout(firstNamePanelLayout);
        firstNamePanelLayout.setHorizontalGroup(
            firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNamePrefixLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstNamePanelLayout.createSequentialGroup()
                        .addComponent(firstNamePrefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(firstNamePanelLayout.createSequentialGroup()
                        .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nicknameTextField)
                            .addComponent(firstNameTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(firstNameSufixLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameSuffixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        firstNamePanelLayout.setVerticalGroup(
            firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstNamePanelLayout.createSequentialGroup()
                .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNamePrefixLabel)
                    .addComponent(firstNamePrefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameSufixLabel)
                    .addComponent(firstNameSuffixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nicknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        familyNamesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("ancestris/modules/editors/genealogyeditor/panels/Bundle").getString("NameEditorPanel.familyNamesPanel.border.title"), new Object[] {}), 0, 0, null, java.awt.Color.white)); // NOI18N

        familyNamesToolBar.setFloatable(false);
        familyNamesToolBar.setRollover(true);

        addFamilyNameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ancestris/modules/editors/genealogyeditor/resources/edit_add.png"))); // NOI18N
        addFamilyNameButton.setFocusable(false);
        addFamilyNameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addFamilyNameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        familyNamesToolBar.add(addFamilyNameButton);

        editFamilyNameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ancestris/modules/editors/genealogyeditor/resources/edit.png"))); // NOI18N
        editFamilyNameButton.setFocusable(false);
        editFamilyNameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editFamilyNameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        familyNamesToolBar.add(editFamilyNameButton);

        deleteFamilyNameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ancestris/modules/editors/genealogyeditor/resources/edit_delete.png"))); // NOI18N
        deleteFamilyNameButton.setFocusable(false);
        deleteFamilyNameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteFamilyNameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        familyNamesToolBar.add(deleteFamilyNameButton);

        familyNamesTable.setModel(familyNamesTableModel);
        familyNamesTable.setColumnSelectionAllowed(true);
        familyNamesScrollPane.setViewportView(familyNamesTable);
        familyNamesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout familyNamesPanelLayout = new javax.swing.GroupLayout(familyNamesPanel);
        familyNamesPanel.setLayout(familyNamesPanelLayout);
        familyNamesPanelLayout.setHorizontalGroup(
            familyNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(familyNamesToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(familyNamesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        familyNamesPanelLayout.setVerticalGroup(
            familyNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyNamesPanelLayout.createSequentialGroup()
                .addComponent(familyNamesToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(familyNamesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(220, 220, 220))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(familyNamesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTypeLabel)
                    .addComponent(nameTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(familyNamesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFamilyNameButton;
    private javax.swing.JButton deleteFamilyNameButton;
    private javax.swing.JButton editFamilyNameButton;
    private javax.swing.JPanel familyNamesPanel;
    private javax.swing.JScrollPane familyNamesScrollPane;
    private javax.swing.JTable familyNamesTable;
    private javax.swing.JToolBar familyNamesToolBar;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JPanel firstNamePanel;
    private javax.swing.JLabel firstNamePrefixLabel;
    private javax.swing.JTextField firstNamePrefixTextField;
    private javax.swing.JTextField firstNameSuffixTextField;
    private javax.swing.JLabel firstNameSufixLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> nameTypeComboBox;
    private javax.swing.JLabel nameTypeLabel;
    private javax.swing.JTextField nicknameTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the name
     */
    public PropertyName getNameToEdit() {
        return nameToEdit;
    }

    /**
     * @param name the name to set
     */
    public void setNameToEdit(PropertyName name) {
        this.nameToEdit = name;
        update();
    }

    private void update() {
        Property nameType = nameToEdit.getProperty("TYPE");
        if (nameType != null) {
            nameTypeComboBox.setSelectedIndex(1);
        } else {
            nameTypeComboBox.setSelectedIndex(1);
        }

        Property namePrefix = nameToEdit.getProperty("NPFX");
        firstNamePrefixTextField.setText(namePrefix != null ? namePrefix.getValue() : "");

        Property givenName = nameToEdit.getProperty("GIVN");
        if (givenName != null) {
            firstNameTextField.setText(givenName.getValue());
        } else {
            firstNameTextField.setText(nameToEdit.getFirstName());
        }

        Property nameSuffix = nameToEdit.getProperty("NSFX");
        firstNameSuffixTextField.setText(nameSuffix != null ? nameSuffix.getValue() : "");

        Property nameNickname = nameToEdit.getProperty("NICK");
        nicknameTextField.setText(nameNickname != null ? nameNickname.getValue() : "");

        Property surname = nameToEdit.getProperty("SURN");
    }
}
